// frontend/app/pages/privacy.vue
<template>
  <PageLayout title="개인정보처리방침" fallback-path="/">
    <div class="legal-page">
      <div class="bg-pattern"></div>
      <main class="main-content">
        <div class="card fade-in" style="animation-delay: 0.1s">
          <h1 class="page-title">Privacy Policy</h1>
          <p class="page-subtitle">개인정보 처리방침</p>

          <div class="legal-content">
            <p class="intro">
              제이지피랩스(이하 "회사")는 개인정보 보호법에 따라 이용자의 개인정보 보호 및 권익을 보호하고 
              개인정보와 관련한 이용자의 고충을 원활하게 처리할 수 있도록 다음과 같은 처리방침을 두고 있습니다.
            </p>

            <section class="legal-section">
              <h2>1. 개인정보의 처리 목적</h2>
              <p>
                회사는 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 
                용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.
              </p>
              <ul>
                <li>회원 가입 및 관리: 회원 가입의사 확인, 회원제 서비스 제공, 회원자격 유지·관리, 서비스 부정이용 방지</li>
                <li>성경통독 서비스: 성경 읽기 진행 상황 기록, 통독 현황 관리, 개인별 진도율 제공</li>
                <li>알림 서비스: 성경통독 리마인더, 서비스 관련 공지사항 전달</li>
                <li>마케팅 및 광고: 이벤트 및 광고성 정보 제공, 서비스 이용 통계</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>2. 수집하는 개인정보 항목</h2>
              <ul>
                <li><strong>필수항목:</strong> 이메일 주소, 이름, 소셜 로그인 식별자</li>
                <li><strong>선택항목:</strong> 프로필 이미지, 닉네임</li>
                <li><strong>자동수집항목:</strong> IP 주소, 쿠키, 서비스 이용 기록, 접속 로그, 기기 정보</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>3. 개인정보의 보유 및 이용기간</h2>
              <p>
                회사는 법령에 따른 개인정보 보유·이용기간 또는 정보주체로부터 개인정보를 수집 시에 동의받은 
                개인정보 보유·이용기간 내에서 개인정보를 처리·보유합니다.
              </p>
              <ul>
                <li>회원 정보: 회원 탈퇴 시까지</li>
                <li>로그인 기록: 3개월 (통신비밀보호법)</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>4. 개인정보의 제3자 제공</h2>
              <p>
                회사는 원칙적으로 이용자의 개인정보를 제3자에게 제공하지 않습니다. 다만, 아래의 경우에는 예외로 합니다.
              </p>
              <ul>
                <li>이용자가 사전에 동의한 경우</li>
                <li>법령의 규정에 의거하거나, 수사 목적으로 법령에 정해진 절차와 방법에 따라 수사기관의 요구가 있는 경우</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>5. 개인정보의 파기</h2>
              <p>
                회사는 개인정보 보유기간의 경과, 처리목적 달성 등 개인정보가 불필요하게 되었을 때에는 지체없이 
                해당 개인정보를 파기합니다. 전자적 파일 형태의 정보는 복구 및 재생되지 않도록 안전하게 삭제하고, 
                그 밖의 기록물은 파쇄 또는 소각합니다.
              </p>
            </section>

            <section class="legal-section">
              <h2>6. 정보주체의 권리·의무 및 행사방법</h2>
              <p>이용자는 개인정보주체로서 다음과 같은 권리를 행사할 수 있습니다.</p>
              <ul>
                <li>개인정보 열람 요구</li>
                <li>오류 등이 있을 경우 정정 요구</li>
                <li>삭제 요구</li>
                <li>처리정지 요구</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>7. 개인정보의 안전성 확보 조치</h2>
              <p>회사는 개인정보의 안전성 확보를 위해 다음과 같은 조치를 취하고 있습니다.</p>
              <ul>
                <li>개인정보의 암호화</li>
                <li>해킹 등에 대비한 기술적 대책</li>
                <li>개인정보에 대한 접근 제한</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>8. 쿠키의 사용</h2>
              <p>
                회사는 이용자에게 개별적인 맞춤서비스를 제공하기 위해 이용정보를 저장하고 수시로 불러오는 
                '쿠키(cookie)'를 사용합니다. 이용자는 웹브라우저 설정을 통해 쿠키 저장을 거부할 수 있으나, 
                이 경우 서비스 이용에 어려움이 있을 수 있습니다.
              </p>
            </section>

            <section class="legal-section">
              <h2>9. 개인정보 보호책임자</h2>
              <ul>
                <li><strong>성명:</strong> 박지건</li>
                <li><strong>연락처:</strong> support@maeil1dok.app</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>10. 권익침해 구제방법</h2>
              <p>개인정보침해에 대한 신고나 상담이 필요하신 경우 아래 기관에 문의하시기 바랍니다.</p>
              <ul>
                <li>개인정보침해신고센터: (국번없이) 118</li>
                <li>개인정보분쟁조정위원회: 1833-6972</li>
                <li>대검찰청 사이버수사과: (국번없이) 1301</li>
                <li>경찰청 사이버안전국: (국번없이) 182</li>
              </ul>
            </section>

            <section class="legal-section">
              <h2>11. 개인정보 처리방침 변경</h2>
              <p>
                이 개인정보 처리방침은 시행일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이 
                있는 경우에는 변경사항의 시행 7일 전부터 공지사항을 통하여 고지할 것입니다.
              </p>
              <p class="effective-date"><strong>시행일:</strong> 2025년 1월 1일</p>
            </section>
          </div>
        </div>

        <div class="link-section fade-in" style="animation-delay: 0.2s">
          <NuxtLink to="/terms" class="link-button">이용약관</NuxtLink>
          <NuxtLink to="/company" class="link-button">회사정보</NuxtLink>
          <NuxtLink to="/" class="link-button">홈으로</NuxtLink>
        </div>
      </main>
    </div>
  </PageLayout>
</template>

<script setup>
import { useHead } from '#imports'
import PageLayout from '~/components/common/PageLayout.vue'

useHead({
  title: '개인정보처리방침 - 매일일독',
  meta: [
    { name: 'description', content: '매일일독 서비스의 개인정보 처리방침입니다.' },
    { property: 'og:title', content: '개인정보처리방침 - 매일일독' },
    { property: 'og:description', content: '매일일독 서비스의 개인정보 처리방침입니다.' },
    { property: 'og:url', content: 'https://maeil1dok.app/privacy' },
    { property: 'og:type', content: 'website' },
  ],
})
</script>

<style scoped>
.legal-page {
  font-family: 'Pretendard', sans-serif;
  background-color: var(--color-bg-primary);
  color: var(--color-text-primary);
  min-height: 100vh;
  position: relative;
  -webkit-font-smoothing: antialiased;
}

.bg-pattern {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: radial-gradient(var(--color-text-tertiary) 1px, transparent 1px);
  background-size: 32px 32px;
  opacity: 0.1;
  z-index: 0;
  pointer-events: none;
}

.main-content {
  padding: 1.5rem 1rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.card {
  background: var(--color-bg-card);
  border-radius: 20px;
  box-shadow: var(--shadow-md);
  overflow: hidden;
  border: 1px solid var(--color-border-light);
  padding: 2rem;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-text-primary);
  margin: 0 0 0.25rem 0;
}

.page-subtitle {
  font-size: 0.95rem;
  color: var(--color-text-secondary);
  margin: 0 0 2rem 0;
}

.legal-content {
  font-size: 0.95rem;
  line-height: 1.7;
}

.intro {
  color: var(--color-text-secondary);
  margin-bottom: 2rem;
  padding-bottom: 1.5rem;
  border-bottom: 1px solid var(--color-border-light);
}

.legal-section {
  margin-bottom: 2rem;
}

.legal-section:last-child {
  margin-bottom: 0;
}

.legal-section h2 {
  font-size: 1.1rem;
  font-weight: 600;
  color: var(--color-text-primary);
  margin: 0 0 0.75rem 0;
}

.legal-section p {
  color: var(--color-text-secondary);
  margin: 0 0 0.75rem 0;
}

.legal-section ul {
  margin: 0;
  padding-left: 1.25rem;
  color: var(--color-text-secondary);
}

.legal-section li {
  margin-bottom: 0.5rem;
}

.legal-section li:last-child {
  margin-bottom: 0;
}

.legal-section strong {
  color: var(--color-text-primary);
  font-weight: 600;
}

.effective-date {
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px dashed var(--color-border-default);
}

.link-section {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  justify-content: center;
}

.link-button {
  padding: 0.6rem 1.25rem;
  background: var(--color-bg-tertiary);
  color: var(--color-text-secondary);
  border: 1px solid var(--color-border-default);
  border-radius: 99px;
  font-size: 0.9rem;
  font-weight: 500;
  text-decoration: none;
  transition: all 0.2s ease;
}

.link-button:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-primary);
  border-color: var(--color-border-dark);
}

/* Animations */
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}

.fade-in {
  opacity: 0;
  animation: fadeIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;
}
</style>

// maeil1dok-next/src/app/(public)/privacy/page.tsx
'use client'

import PageHeader from '@/components/ui/PageHeader'
import Link from 'next/link'

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      <PageHeader title="개인정보처리방침" fallback-path="/" />

      <div className="max-w-[768px] mx-auto px-4 py-6">
        <div className="bg-[var(--color-bg-card)] rounded-[20px] shadow-[var(--shadow-md)] border border-[var(--color-border-light)] p-8">
          <h1 className="text-2xl font-bold text-[var(--color-text-primary)] mb-1">Privacy Policy</h1>
          <p className="text-sm text-[var(--color-text-secondary)] mb-8">개인정보 처리방침</p>

          <div className="space-y-6 text-sm leading-relaxed">
            <p className="text-[var(--color-text-secondary)] pb-6 border-b border-[var(--color-border-light)]">
              제이지피랩스(이하 "회사")는 개인정보 보호법에 따라 이용자의 개인정보 보호 및 권익을 보호하고 
              개인정보와 관련한 이용자의 고충을 원활하게 처리할 수 있도록 다음과 같은 처리방침을 두고 있습니다.
            </p>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">1. 개인정보의 처리 목적</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">
                회사는 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 
                용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>회원 가입 및 관리: 회원 가입의사 확인, 회원제 서비스 제공, 회원자격 유지·관리, 서비스 부정이용 방지</li>
                <li>성경통독 서비스: 성경 읽기 진행 상황 기록, 통독 현황 관리, 개인별 진도율 제공</li>
                <li>알림 서비스: 성경통독 리마인더, 서비스 관련 공지사항 전달</li>
                <li>마케팅 및 광고: 이벤트 및 광고성 정보 제공, 서비스 이용 통계</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">2. 수집하는 개인정보 항목</h2>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li><strong className="text-[var(--color-text-primary)]">필수항목:</strong> 이메일 주소, 이름, 소셜 로그인 식별자</li>
                <li><strong className="text-[var(--color-text-primary)]">선택항목:</strong> 프로필 이미지, 닉네임</li>
                <li><strong className="text-[var(--color-text-primary)]">자동수집항목:</strong> IP 주소, 쿠키, 서비스 이용 기록, 접속 로그, 기기 정보</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">3. 개인정보의 보유 및 이용기간</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">
                회사는 법령에 따른 개인정보 보유·이용기간 또는 정보주체로부터 개인정보를 수집 시에 동의받은 
                개인정보 보유·이용기간 내에서 개인정보를 처리·보유합니다.
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>회원 정보: 회원 탈퇴 시까지</li>
                <li>로그인 기록: 3개월 (통신비밀보호법)</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">4. 개인정보의 제3자 제공</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">
                회사는 원칙적으로 이용자의 개인정보를 제3자에게 제공하지 않습니다. 다만, 아래의 경우에는 예외로 합니다.
              </p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>이용자가 사전에 동의한 경우</li>
                <li>법령의 규정에 의거하거나, 수사 목적으로 법령에 정해진 절차와 방법에 따라 수사기관의 요구가 있는 경우</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">5. 개인정보의 파기</h2>
              <p className="text-[var(--color-text-secondary)]">
                회사는 개인정보 보유기간의 경과, 처리목적 달성 등 개인정보가 불필요하게 되었을 때에는 지체없이 
                해당 개인정보를 파기합니다. 전자적 파일 형태의 정보는 복구 및 재생되지 않도록 안전하게 삭제하고, 
                그 밖의 기록물은 파쇄 또는 소각합니다.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">6. 정보주체의 권리·의무 및 행사방법</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">이용자는 개인정보주체로서 다음과 같은 권리를 행사할 수 있습니다.</p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>개인정보 열람 요구</li>
                <li>오류 등이 있을 경우 정정 요구</li>
                <li>삭제 요구</li>
                <li>처리정지 요구</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">7. 개인정보의 안전성 확보 조치</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">회사는 개인정보의 안전성 확보를 위해 다음과 같은 조치를 취하고 있습니다.</p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>개인정보의 암호화</li>
                <li>해킹 등에 대비한 기술적 대책</li>
                <li>개인정보에 대한 접근 제한</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">8. 쿠키의 사용</h2>
              <p className="text-[var(--color-text-secondary)]">
                회사는 이용자에게 개별적인 맞춤서비스를 제공하기 위해 이용정보를 저장하고 수시로 불러오는 
                '쿠키(cookie)'를 사용합니다. 이용자는 웹브라우저 설정을 통해 쿠키 저장을 거부할 수 있으나, 
                이 경우 서비스 이용에 어려움이 있을 수 있습니다.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">9. 개인정보 보호책임자</h2>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li><strong className="text-[var(--color-text-primary)]">성명:</strong> 박지건</li>
                <li><strong className="text-[var(--color-text-primary)]">연락처:</strong> support@maeil1dok.app</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">10. 권익침해 구제방법</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">개인정보침해에 대한 신고나 상담이 필요하신 경우 아래 기관에 문의하시기 바랍니다.</p>
              <ul className="list-disc list-inside space-y-2 text-[var(--color-text-secondary)] pl-2">
                <li>개인정보침해신고센터: (국번없이) 118</li>
                <li>개인정보분쟁조정위원회: 1833-6972</li>
                <li>대검찰청 사이버수사과: (국번없이) 1301</li>
                <li>경찰청 사이버안전국: (국번없이) 182</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)]">11. 개인정보 처리방침 변경</h2>
              <p className="text-[var(--color-text-secondary)] mb-2">
                이 개인정보 처리방침은 시행일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이 
                있는 경우에는 변경사항의 시행 7일 전부터 공지사항을 통하여 고지할 것입니다.
              </p>
              <p className="text-[var(--color-text-secondary)] pt-4 border-t border-dashed border-[var(--color-border-default)]">
                <strong className="text-[var(--color-text-primary)]">시행일:</strong> 2025년 1월 1일
              </p>
            </section>
          </div>
        </div>

        <div className="flex flex-wrap gap-3 justify-center mt-6">
          <Link href="/terms" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            이용약관
          </Link>
          <Link href="/company" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            회사정보
          </Link>
          <Link href="/" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            홈으로
          </Link>
        </div>
      </div>
    </div>
  )
}
