// maeil1dok-next/src/components/bible/BibleHome.tsx
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'

import { BIBLE_BOOKS } from '@/lib/bible/books'
import { cn } from '@/lib/utils'

// ─── Types ───────────────────────────────────────────────────────────────────

interface BibleHomeProps {
  lastPosition?: { book: string; chapter: number }
  onContinueReading: (book: string, chapter: number) => void
  onSelectBook: (book: string, chapter: number) => void
  onViewTOC: () => void
}

interface TodaySchedule {
  id: string
  bookCode: string
  bookName: string
  range: string
  startChapter: number
  endChapter: number
  total: number
  completed: number
  isCompleted: boolean
  planId: number
}

interface RecentRecord {
  book: string
  bookName: string
  chapter: number
  readDate: string
}

interface HomeStats {
  bookmarkCount: number
  noteCount: number
  highlightCount: number
  recentRecords: RecentRecord[]
}

// ─── Icons (inline SVGs) ─────────────────────────────────────────────────────

function PlayIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-[18px] w-[18px]', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
}

function CheckCircleIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-[18px] w-[18px]', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
}

function ArrowRightIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  )
}

function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-[18px] w-[18px]', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  )
}

function SettingsIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M11.049 2.927c.3-1.14 1.603-1.14 1.902 0a1 1 0 00.95.69 1 1 0 011.12.743 1 1 0 001.341.667c1.004-.468 1.926.454 1.458 1.458a1 1 0 00.667 1.34 1 1 0 01.743 1.121 1 1 0 00.69.95c1.14.3 1.14 1.603 0 1.902a1 1 0 00-.69.95 1 1 0 01-.743 1.12 1 1 0 00-.667 1.341c.468 1.004-.454 1.926-1.458 1.458a1 1 0 00-1.34.667 1 1 0 01-1.121.743 1 1 0 00-.95.69c-.3 1.14-1.603 1.14-1.902 0a1 1 0 00-.95-.69 1 1 0 01-1.12-.743 1 1 0 00-1.341-.667c-1.004.468-1.926-.454-1.458-1.458a1 1 0 00-.667-1.34 1 1 0 01-.743-1.121 1 1 0 00-.69-.95c-1.14-.3-1.14-1.603 0-1.902a1 1 0 00.69-.95 1 1 0 01.743-1.12 1 1 0 00.667-1.341c-.468-1.004.454-1.926 1.458-1.458a1 1 0 001.34-.667 1 1 0 011.121-.743 1 1 0 00.95-.69z"
      />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  )
}

function BookmarkIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
    </svg>
  )
}

function DocumentIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
    </svg>
  )
}

function HighlightIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M4 7h16M4 12h16M4 17h16"
      />
    </svg>
  )
}

function HistoryIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  )
}

function ListIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-5 w-5', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h10" />
    </svg>
  )
}

function InfoIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-4 w-4', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01" />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 22a10 10 0 100-20 10 10 0 000 20z" />
    </svg>
  )
}

function CalendarIcon({ className }: { className?: string }) {
  return (
    <svg aria-hidden="true" className={cn('h-[18px] w-[18px]', className)} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
  )
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getBookName(bookCode: string): string {
  return BIBLE_BOOKS[bookCode]?.ko ?? bookCode
}

function getChapterUnit(bookCode: string): string {
  return bookCode === 'psa' ? '편' : '장'
}

function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  const today = new Date()
  const diff = Math.floor((today.getTime() - date.getTime()) / (1000 * 60 * 60 * 24))

  if (diff === 0) return '오늘'
  if (diff === 1) return '어제'
  if (diff < 7) return `${diff}일 전`

  return date.toLocaleDateString('ko-KR', { month: 'short', day: 'numeric' })
}

function formatTodayDate(): string {
  const today = new Date()
  return today.toLocaleDateString('ko-KR', { month: 'long', day: 'numeric', weekday: 'short' })
}

// ─── Component ───────────────────────────────────────────────────────────────

export default function BibleHome({
  lastPosition,
  onContinueReading,
  onSelectBook,
  onViewTOC,
}: BibleHomeProps) {
  const router = useRouter()

  const [todaySchedule, setTodaySchedule] = useState<TodaySchedule | null>(null)
  const [stats, setStats] = useState<HomeStats>({
    bookmarkCount: 0,
    noteCount: 0,
    highlightCount: 0,
    recentRecords: [],
  })
  const [isLoading, setIsLoading] = useState(true)
  const [hasPlan, setHasPlan] = useState(false)
  const [isAuthenticated, setIsAuthenticated] = useState(true)
  const [tipsDismissed, setTipsDismissed] = useState(false)

  const hasBookmarks = stats.bookmarkCount > 0
  const hasNotes = stats.noteCount > 0
  const hasHighlights = stats.highlightCount > 0

  const showWelcomeGuide = useMemo(
    () => !lastPosition && !todaySchedule && stats.recentRecords.length === 0,
    [lastPosition, todaySchedule, stats.recentRecords.length],
  )

  const showUsageTips = useMemo(() => {
    if (tipsDismissed) return false
    const totalActivity = stats.bookmarkCount + stats.noteCount + stats.highlightCount
    return totalActivity < 3 && (!hasBookmarks || !hasNotes || !hasHighlights)
  }, [tipsDismissed, stats.bookmarkCount, stats.noteCount, stats.highlightCount, hasBookmarks, hasNotes, hasHighlights])

  const canDismissTips = stats.bookmarkCount + stats.noteCount + stats.highlightCount > 0

  // ─── Data fetching ──────────────────────────────────────────────────────

  const loadHomeStats = useCallback(async () => {
    try {
      const [bookmarksRes, notesRes, highlightsRes, recordsRes] = await Promise.all([
        fetch('/api/bible/bookmarks').then((r) => (r.ok ? r.json() : null)).catch(() => null),
        fetch('/api/bible/notes').then((r) => (r.ok ? r.json() : null)).catch(() => null),
        fetch('/api/bible/highlights').then((r) => (r.ok ? r.json() : null)).catch(() => null),
        fetch('/api/bible/personal-records').then((r) => (r.ok ? r.json() : null)).catch(() => null),
      ])

      const bookmarks = bookmarksRes?.data ?? []
      const notes = notesRes?.data ?? []
      const highlights = highlightsRes?.data ?? []
      const records = (recordsRes?.data ?? []).slice(0, 5)

      setStats({
        bookmarkCount: bookmarks.length,
        noteCount: notes.length,
        highlightCount: highlights.length,
        recentRecords: records.map((r: { book: string; chapter: number; read_date: string }) => ({
          book: r.book,
          bookName: getBookName(r.book),
          chapter: r.chapter,
          readDate: r.read_date,
        })),
      })

      if (!bookmarksRes && !notesRes && !highlightsRes && !recordsRes) {
        setIsAuthenticated(false)
      }
    } catch {
      // Silently fail - stats will remain at defaults
    }
  }, [])

  const loadTodaySchedule = useCallback(async () => {
    try {
      const res = await fetch('/api/bible/schedules/today')
      if (res.status === 401) {
        setIsAuthenticated(false)
        return
      }

      if (!res.ok) return

      const result = await res.json()
      const schedules = result.data
      if (!schedules || schedules.length === 0) {
        setHasPlan(false)
        setTodaySchedule(null)
        return
      }

      setHasPlan(true)

      const firstSchedule = schedules[0]
      const completedCount = schedules.filter((s: { is_completed: boolean }) => s.is_completed).length

      const bookCode = firstSchedule.book_code ?? firstSchedule.book ?? ''
      const startCh = firstSchedule.start_chapter ?? firstSchedule.startChapter ?? 1
      const endCh = firstSchedule.end_chapter ?? firstSchedule.endChapter ?? startCh
      const unit = getChapterUnit(bookCode)

      let range = `${startCh}${unit}`
      if (endCh && endCh !== startCh) {
        range = `${startCh}-${endCh}${unit}`
      }

      setTodaySchedule({
        id: firstSchedule.id,
        bookCode,
        bookName: getBookName(bookCode),
        range,
        startChapter: startCh,
        endChapter: endCh,
        total: schedules.length,
        completed: completedCount,
        isCompleted: completedCount === schedules.length,
        planId: firstSchedule.plan_id ?? firstSchedule.planId ?? 0,
      })
    } catch {
      // Silently fail
    }
  }, [])

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setTipsDismissed(localStorage.getItem('bible_tips_dismissed') === 'true')
    }

    setIsLoading(true)
    void Promise.all([loadHomeStats(), loadTodaySchedule()]).finally(() => {
      setIsLoading(false)
    })
  }, [loadHomeStats, loadTodaySchedule])

  // ─── Handlers ───────────────────────────────────────────────────────────

  const handleStartTongdok = useCallback(() => {
    if (!todaySchedule) return
    const { bookCode, startChapter, id, planId } = todaySchedule
    router.push(
      `/bible?book=${bookCode}&chapter=${startChapter}&tongdok=true&schedule=${id}&plan=${planId}`,
    )
  }, [todaySchedule, router])

  const handleRecordClick = useCallback(
    (record: RecentRecord) => {
      onSelectBook(record.book, record.chapter)
    },
    [onSelectBook],
  )

  const dismissTips = useCallback(() => {
    setTipsDismissed(true)
    if (typeof window !== 'undefined') {
      localStorage.setItem('bible_tips_dismissed', 'true')
    }
  }, [])

  // ─── Render ─────────────────────────────────────────────────────────────

  return (
    <div className="min-h-dvh bg-[var(--color-bg-primary)]">
      {/* Header */}
      <header
        className={cn(
          'sticky top-0 z-10 flex items-center justify-between',
          'border-b border-[var(--color-border-default)] bg-[var(--color-bg-secondary)]',
          'px-4 py-3',
        )}
      >
        <h1 className="text-xl font-bold text-[var(--color-text-primary)]">성경</h1>
        <button
          type="button"
          className={cn(
            'rounded-lg p-2 text-[var(--color-text-secondary)] transition-all',
            'hover:bg-[var(--color-bg-tertiary)] hover:text-[var(--color-text-primary)]',
          )}
          onClick={() => router.push('/bible/settings')}
          aria-label="성경 설정"
        >
          <SettingsIcon />
        </button>
      </header>

      <div className="space-y-6 p-4 pb-8">
        {/* ── Today's Reading Card ─────────────────────────────────────── */}
        {todaySchedule && (
          <section>
            <div
              className={cn(
                'rounded-2xl p-5 text-white shadow-lg',
                'bg-gradient-to-br from-[var(--color-accent-primary)] to-[var(--color-accent-hover)]',
              )}
            >
              {/* Card header */}
              <div className="mb-4 flex items-center justify-between">
                <span className="rounded-full bg-white/20 px-3 py-1 text-xs font-semibold">
                  오늘의 통독
                </span>
                <span className="text-[0.8125rem] opacity-90">{formatTodayDate()}</span>
              </div>

              {/* Schedule info */}
              <div className="mb-4">
                <div className="mb-3 flex items-baseline gap-2">
                  <span className="text-xl font-bold">{todaySchedule.bookName}</span>
                  <span className="text-base opacity-90">{todaySchedule.range}</span>
                </div>

                {/* Progress indicator */}
                {todaySchedule.total > 1 && (
                  <div className="flex items-center gap-3">
                    <span className="whitespace-nowrap text-xs opacity-90">
                      {todaySchedule.completed}/{todaySchedule.total} 완료
                    </span>
                    <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/30">
                      <div
                        className="h-full rounded-full bg-white transition-all duration-300"
                        style={{
                          width: `${(todaySchedule.completed / todaySchedule.total) * 100}%`,
                        }}
                      />
                    </div>
                  </div>
                )}
              </div>

              {/* Start button */}
              <button
                type="button"
                className={cn(
                  'flex w-full items-center justify-center gap-2 rounded-xl py-3.5 text-[0.9375rem] font-semibold transition-all',
                  todaySchedule.isCompleted
                    ? 'bg-white/20 text-white'
                    : 'bg-white text-[var(--color-accent-primary)] hover:-translate-y-0.5 hover:shadow-lg',
                )}
                onClick={handleStartTongdok}
              >
                {todaySchedule.isCompleted ? (
                  <>
                    <CheckCircleIcon />
                    <span>완료됨</span>
                  </>
                ) : (
                  <>
                    <PlayIcon />
                    <span>통독 시작</span>
                  </>
                )}
              </button>
            </div>
          </section>
        )}

        {!hasPlan && isAuthenticated && !isLoading && (
          <section>
            <div
              className={cn(
                'flex items-center gap-2 rounded-[10px] bg-[var(--color-bg-tertiary)] p-3',
                'text-[0.8125rem] text-[var(--color-text-secondary)]',
              )}
            >
              <InfoIcon />
              <span>플랜을 구독하면 매일 통독 일정을 받을 수 있어요</span>
              <button
                type="button"
                className="ml-auto font-medium text-[var(--color-accent-primary)]"
                onClick={() => router.push('/plan')}
              >
                플랜 보기
              </button>
            </div>
          </section>
        )}

        {/* ── Continue Reading ─────────────────────────────────────────── */}
        {lastPosition && (
          <section>
            <h2 className="mb-3 text-sm font-semibold text-[var(--color-text-primary)]">
              계속 읽기
            </h2>
            <button
              type="button"
              className={cn(
                'flex w-full items-center justify-between rounded-xl border border-[var(--color-border-default)]',
                'bg-[var(--color-bg-secondary)] px-5 py-4 text-[var(--color-text-primary)]',
                'transition-all hover:border-[var(--color-accent-primary)] hover:bg-[var(--color-bg-tertiary)]',
              )}
              onClick={() => onContinueReading(lastPosition.book, lastPosition.chapter)}
            >
              <div className="flex items-center gap-2">
                <span className="font-semibold">
                  {BIBLE_BOOKS[lastPosition.book]?.ko ?? lastPosition.book}
                </span>
                <span className="text-[0.9375rem] text-[var(--color-text-secondary)]">
                  {lastPosition.chapter}
                  {getChapterUnit(lastPosition.book)}
                </span>
              </div>
              <ArrowRightIcon className="text-[var(--color-text-muted)]" />
            </button>
          </section>
        )}

        {/* ── Welcome Guide ────────────────────────────────────────────── */}
        {showWelcomeGuide && !isLoading && (
          <section>
            <div
              className={cn(
                'rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)]',
                'px-6 py-8 text-center',
              )}
            >
              <div className="mb-4 text-5xl">📖</div>
              <h2 className="mb-2 text-lg font-bold text-[var(--color-text-primary)]">
                매일일독에 오신 것을 환영합니다!
              </h2>
              <p className="mb-6 text-[0.9375rem] text-[var(--color-text-secondary)]">
                성경을 읽고, 묵상하고, 기록해보세요.
              </p>
              <div className="flex flex-col gap-3">
                <button
                  type="button"
                  className={cn(
                    'flex items-center justify-center gap-2 rounded-xl px-4 py-3.5',
                    'bg-[var(--color-accent-primary)] text-[0.9375rem] font-medium text-white',
                    'transition-all hover:bg-[var(--color-accent-hover)]',
                  )}
                  onClick={onViewTOC}
                >
                  <ListIcon className="h-[18px] w-[18px]" />
                  성경 목차에서 시작하기
                </button>
                {isAuthenticated && (
                  <button
                    type="button"
                    className={cn(
                      'flex items-center justify-center gap-2 rounded-[10px] border border-[var(--color-border-default)] px-4 py-3.5',
                      'bg-[var(--color-bg-tertiary)] text-[0.9375rem] font-medium text-[var(--color-text-primary)]',
                      'transition-all hover:bg-[var(--color-bg-primary)]',
                    )}
                    onClick={() => router.push('/plan')}
                  >
                    <CalendarIcon />
                    통독 플랜 구독하기
                  </button>
                )}
              </div>
            </div>
          </section>
        )}

        {/* ── Feature Cards ────────────────────────────────────────────── */}
        <section>
          <h2 className="mb-3 text-sm font-semibold text-[var(--color-text-primary)]">
            내 성경 활동
          </h2>
          <div className="flex flex-col gap-2">
            <FeatureCard
              icon={<BookmarkIcon />}
              iconBg="bg-[var(--color-warning-bg)]"
              iconColor="text-[var(--color-warning-text)]"
              name="북마크"
              count={stats.bookmarkCount}
              description={
                stats.bookmarkCount > 0
                  ? `저장된 ${stats.bookmarkCount}개의 장`
                  : '자주 찾는 장을 저장하세요'
              }
              onClick={() => router.push('/bible/bookmarks')}
            />
            <FeatureCard
              icon={<DocumentIcon />}
              iconBg="bg-[var(--color-info-bg)]"
              iconColor="text-[var(--color-info-text)]"
              name="묵상노트"
              count={stats.noteCount}
              description={
                stats.noteCount > 0
                  ? `작성된 ${stats.noteCount}개의 노트`
                  : '말씀을 읽고 묵상을 기록하세요'
              }
              onClick={() => router.push('/bible/notes')}
            />
            <FeatureCard
              icon={<HighlightIcon />}
              iconBg="bg-[var(--color-danger-bg)]"
              iconColor="text-[var(--color-danger-text)]"
              name="하이라이트"
              count={stats.highlightCount}
              description={
                stats.highlightCount > 0
                  ? `표시된 ${stats.highlightCount}개의 구절`
                  : '중요한 구절에 색상을 입히세요'
              }
              onClick={() => router.push('/bible/highlights')}
            />
            <FeatureCard
              icon={<HistoryIcon />}
              iconBg="bg-[var(--color-success-bg)]"
              iconColor="text-[var(--color-success-text)]"
              name="읽기 기록"
              description="읽은 장과 날짜를 확인하세요"
              onClick={() => router.push('/bible/history')}
            />
          </div>
        </section>

        {/* ── Usage Tips ───────────────────────────────────────────────── */}
        {showUsageTips && (
          <section
            className={cn(
              'rounded-xl border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)] p-4',
            )}
          >
            <h2 className="mb-3 text-sm font-semibold text-[var(--color-text-primary)]">
              💡 사용 팁
            </h2>
            <div className="flex flex-col gap-3.5">
              {!hasHighlights && (
                <TipItem
                  emoji="✨"
                  title="하이라이트 만들기"
                  description={
                    <>
                      성경 본문에서 텍스트를{' '}
                      <em className="not-italic font-medium text-[var(--color-accent-primary)]">
                        드래그
                      </em>
                      하면 하이라이트, 복사, 공유 메뉴가 나타나요
                    </>
                  }
                />
              )}
              {!hasBookmarks && (
                <TipItem
                  emoji="🔖"
                  title="북마크 추가하기"
                  description={
                    <>
                      성경 읽기 화면 상단의{' '}
                      <em className="not-italic font-medium text-[var(--color-accent-primary)]">
                        북마크 아이콘
                      </em>
                      을 눌러 현재 장을 저장하세요
                    </>
                  }
                />
              )}
              {!hasNotes && (
                <TipItem
                  emoji="📝"
                  title="묵상노트 작성하기"
                  description={
                    <>
                      읽기 화면의{' '}
                      <em className="not-italic font-medium text-[var(--color-accent-primary)]">
                        메뉴(⋮)
                      </em>
                      에서 묵상노트를 작성할 수 있어요
                    </>
                  }
                />
              )}
            </div>
            {canDismissTips && (
              <button
                type="button"
                className={cn(
                  'mt-3 block w-full text-center text-xs text-[var(--color-text-muted)]',
                  'transition-colors hover:text-[var(--color-text-secondary)]',
                )}
                onClick={dismissTips}
              >
                다음부터 표시 안함
              </button>
            )}
          </section>
        )}

        {/* ── Recent Records ───────────────────────────────────────────── */}
        {stats.recentRecords.length > 0 && (
          <section>
            <h2 className="mb-3 text-sm font-semibold text-[var(--color-text-primary)]">
              최근 읽은 성경
            </h2>
            <ul
              className={cn(
                'overflow-hidden rounded-xl border border-[var(--color-border-default)]',
                'bg-[var(--color-bg-secondary)]',
              )}
            >
              {stats.recentRecords.map((record) => (
                <li
                  key={`${record.book}-${record.chapter}-${record.readDate}`}
                  className="border-b border-[var(--color-border-default)] last:border-b-0"
                >
                  <button
                    type="button"
                    className={cn(
                      'flex w-full items-center justify-between px-4 py-3.5 text-left',
                      'transition-colors hover:bg-[var(--color-bg-tertiary)]',
                    )}
                    onClick={() => handleRecordClick(record)}
                  >
                    <span className="text-[0.9375rem] text-[var(--color-text-primary)]">
                      {record.bookName} {record.chapter}
                      {getChapterUnit(record.book)}
                    </span>
                    <span className="text-xs text-[var(--color-text-muted)]">
                      {formatDate(record.readDate)}
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* ── TOC Shortcut ─────────────────────────────────────────────── */}
        <section>
          <button
            type="button"
            className={cn(
              'flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--color-border-default)]',
              'bg-[var(--color-bg-secondary)] py-3.5 text-[0.9375rem] text-[var(--color-text-primary)]',
              'transition-all hover:border-[var(--color-accent-primary)] hover:bg-[var(--color-bg-tertiary)]',
            )}
            onClick={onViewTOC}
          >
            <ListIcon className="text-[var(--color-accent-primary)]" />
            성경 전체 목차
          </button>
        </section>
      </div>
    </div>
  )
}

// ─── Sub-components ────────────────────────────────────────────────────────

interface FeatureCardProps {
  icon: React.ReactNode
  iconBg: string
  iconColor: string
  name: string
  count?: number
  description: string
  onClick: () => void
}

function FeatureCard({ icon, iconBg, iconColor, name, count, description, onClick }: FeatureCardProps) {
  return (
    <button
      type="button"
      className={cn(
        'flex w-full items-center gap-3.5 rounded-xl border border-[var(--color-border-default)]',
        'bg-[var(--color-bg-secondary)] p-4 text-left',
        'transition-all hover:border-[var(--color-border-dark)] hover:bg-[var(--color-bg-tertiary)]',
      )}
      onClick={onClick}
    >
      <div
        className={cn(
          'flex h-11 w-11 shrink-0 items-center justify-center rounded-xl',
          iconBg,
          iconColor,
        )}
      >
        {icon}
      </div>
      <div className="min-w-0 flex-1 text-left">
        <div className="mb-0.5 flex items-center gap-2">
          <span className="text-[0.9375rem] font-semibold text-[var(--color-text-primary)]">
            {name}
          </span>
          {count != null && count > 0 && (
            <span
              className={cn(
                'rounded-lg bg-[var(--color-accent-light)] px-2 py-0.5',
                'text-xs font-semibold text-[var(--color-accent-primary)]',
              )}
            >
              {count}
            </span>
          )}
        </div>
        <p className="truncate text-[0.8125rem] text-[var(--color-text-secondary)]">
          {description}
        </p>
      </div>
      <ChevronRightIcon className="shrink-0 text-[var(--color-text-muted)]" />
    </button>
  )
}

interface TipItemProps {
  emoji: string
  title: string
  description: React.ReactNode
}

function TipItem({ emoji, title, description }: TipItemProps) {
  return (
    <div className="flex gap-3 rounded-lg bg-[var(--color-bg-tertiary)] p-3">
      <span className="shrink-0 text-xl">{emoji}</span>
      <div>
        <strong className="mb-1 block text-sm text-[var(--color-text-primary)]">{title}</strong>
        <p className="text-[0.8125rem] leading-relaxed text-[var(--color-text-secondary)]">
          {description}
        </p>
      </div>
    </div>
  )
}

// frontend/app/components/bible/BibleHome.vue
<template>
  <div class="bible-home">
    <header class="home-header">
      <h1>성경</h1>
      <button class="settings-btn" @click="$router.push('/bible/settings')">
        <SettingsIcon :size="20" />
      </button>
    </header>

    <div class="home-content">
      <!-- 오늘의 통독 카드 (플랜 구독 시) -->
      <section v-if="todaySchedule" class="today-tongdok-section">
        <div class="today-card">
          <div class="today-card-header">
            <span class="today-badge">오늘의 통독</span>
            <span class="today-date">{{ formatTodayDate() }}</span>
          </div>
          <div class="today-card-body">
            <div class="today-schedule">
              <span class="schedule-book">{{ todaySchedule.book_name }}</span>
              <span class="schedule-range">{{ todaySchedule.range }}</span>
            </div>
            <div class="today-progress" v-if="todaySchedule.total > 1">
              <span class="progress-label">{{ todaySchedule.completed }}/{{ todaySchedule.total }} 완료</span>
              <div class="mini-progress-bar">
                <div class="mini-progress-fill" :style="{ width: `${(todaySchedule.completed / todaySchedule.total) * 100}%` }"></div>
              </div>
            </div>
          </div>
          <button
            class="today-start-btn"
            :class="{ 'is-completed': todaySchedule.isCompleted }"
            @click="startTodayTongdok"
          >
            <template v-if="todaySchedule.isCompleted">
              <CheckCircleIcon :size="18" />
              <span>완료됨</span>
            </template>
            <template v-else>
              <PlayIcon :size="18" />
              <span>통독 시작</span>
            </template>
          </button>
        </div>

        <!-- 플랜이 없는 경우 안내 -->
        <div v-if="!hasPlan && isAuthenticated" class="no-plan-hint">
          <InfoIcon :size="16" />
          <span>플랜을 구독하면 매일 통독 일정을 받을 수 있어요</span>
          <NuxtLink to="/plans" class="plan-link">플랜 보기</NuxtLink>
        </div>
      </section>

      <!-- 계속 읽기 -->
      <section v-if="lastPosition" class="continue-section">
        <h2 class="section-title">계속 읽기</h2>
        <button class="continue-card" @click="$emit('continue-reading')">
          <div class="continue-info">
            <span class="book-name">{{ lastPosition.book_name }}</span>
            <span class="chapter">{{ lastPosition.chapter }}{{ getChapterUnit(lastPosition.book) }}</span>
          </div>
          <ArrowRightIcon :size="20" />
        </button>
      </section>

      <!-- 첫 방문자 가이드 (통독도 없고 마지막 위치도 없을 때) -->
      <section v-if="showWelcomeGuide" class="welcome-section">
        <div class="welcome-card">
          <div class="welcome-icon">📖</div>
          <h2>매일일독에 오신 것을 환영합니다!</h2>
          <p>성경을 읽고, 묵상하고, 기록해보세요.</p>
          <div class="welcome-actions">
            <button class="welcome-btn primary" @click="$emit('show-toc')">
              <ListIcon :size="18" />
              성경 목차에서 시작하기
            </button>
            <NuxtLink v-if="isAuthenticated" to="/plans" class="welcome-btn secondary">
              <CalendarIcon :size="18" />
              통독 플랜 구독하기
            </NuxtLink>
          </div>
        </div>
      </section>

      <!-- 기능 안내 (빠른 접근 개선) -->
      <section class="features-section">
        <h2 class="section-title">내 성경 활동</h2>

        <div class="feature-list">
          <!-- 북마크 -->
          <button class="feature-card" @click="$router.push('/bible/bookmarks')">
            <div class="feature-icon bookmark">
              <BookmarkIcon :size="20" />
            </div>
            <div class="feature-content">
              <div class="feature-header">
                <span class="feature-name">북마크</span>
                <span v-if="bookmarkCount > 0" class="feature-count">{{ bookmarkCount }}</span>
              </div>
              <p class="feature-desc">
                {{ bookmarkCount > 0 ? `저장된 ${bookmarkCount}개의 장` : '자주 찾는 장을 저장하세요' }}
              </p>
            </div>
            <ChevronRightIcon :size="18" class="feature-arrow" />
          </button>

          <!-- 묵상노트 -->
          <button class="feature-card" @click="$router.push('/bible/notes')">
            <div class="feature-icon note">
              <DocumentIcon :size="20" />
            </div>
            <div class="feature-content">
              <div class="feature-header">
                <span class="feature-name">묵상노트</span>
                <span v-if="noteCount > 0" class="feature-count">{{ noteCount }}</span>
              </div>
              <p class="feature-desc">
                {{ noteCount > 0 ? `작성된 ${noteCount}개의 노트` : '말씀을 읽고 묵상을 기록하세요' }}
              </p>
            </div>
            <ChevronRightIcon :size="18" class="feature-arrow" />
          </button>

          <!-- 하이라이트 -->
          <button class="feature-card" @click="$router.push('/bible/highlights')">
            <div class="feature-icon highlight">
              <LayersIcon :size="20" />
            </div>
            <div class="feature-content">
              <div class="feature-header">
                <span class="feature-name">하이라이트</span>
                <span v-if="highlightCount > 0" class="feature-count">{{ highlightCount }}</span>
              </div>
              <p class="feature-desc">
                {{ highlightCount > 0 ? `표시된 ${highlightCount}개의 구절` : '중요한 구절에 색상을 입히세요' }}
              </p>
            </div>
            <ChevronRightIcon :size="18" class="feature-arrow" />
          </button>

          <!-- 읽기 기록 -->
          <button class="feature-card" @click="$router.push('/bible/history')">
            <div class="feature-icon history">
              <HistoryIcon :size="20" />
            </div>
            <div class="feature-content">
              <div class="feature-header">
                <span class="feature-name">읽기 기록</span>
              </div>
              <p class="feature-desc">읽은 장과 날짜를 확인하세요</p>
            </div>
            <ChevronRightIcon :size="18" class="feature-arrow" />
          </button>
        </div>
      </section>

      <!-- 사용 팁 (첫 방문 또는 활동이 적을 때) -->
      <section v-if="showUsageTips" class="tips-section">
        <h2 class="section-title">💡 사용 팁</h2>
        <div class="tips-list">
          <div class="tip-item" v-if="!hasHighlights">
            <div class="tip-icon">✨</div>
            <div class="tip-content">
              <strong>하이라이트 만들기</strong>
              <p>성경 본문에서 텍스트를 <em>드래그</em>하면 하이라이트, 복사, 공유 메뉴가 나타나요</p>
            </div>
          </div>
          <div class="tip-item" v-if="!hasBookmarks">
            <div class="tip-icon">🔖</div>
            <div class="tip-content">
              <strong>북마크 추가하기</strong>
              <p>성경 읽기 화면 상단의 <em>북마크 아이콘</em>을 눌러 현재 장을 저장하세요</p>
            </div>
          </div>
          <div class="tip-item" v-if="!hasNotes">
            <div class="tip-icon">📝</div>
            <div class="tip-content">
              <strong>묵상노트 작성하기</strong>
              <p>읽기 화면의 <em>메뉴(⋮)</em>에서 묵상노트를 작성할 수 있어요</p>
            </div>
          </div>
        </div>
        <button v-if="canDismissTips" class="dismiss-tips-btn" @click="dismissTips">
          다음부터 표시 안함
        </button>
      </section>

      <!-- 최근 읽은 기록 -->
      <section v-if="recentRecords.length > 0" class="recent-section">
        <h2 class="section-title">최근 읽은 성경</h2>
        <ul class="recent-list">
          <li
            v-for="record in recentRecords"
            :key="`${record.book}-${record.chapter}`"
            @click="handleRecordClick(record)"
          >
            <span class="record-location">
              {{ record.book_name }} {{ record.chapter }}{{ getChapterUnit(record.book) }}
            </span>
            <span class="record-date">
              {{ formatDate(record.read_date) }}
            </span>
          </li>
        </ul>
      </section>

      <!-- 성경 전체 보기 -->
      <section class="toc-shortcut">
        <button class="toc-btn" @click="$emit('show-toc')">
          <ListIcon :size="20" />
          성경 전체 목차
        </button>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useApi } from '~/composables/useApi';
import { useReadingPosition } from '~/composables/useReadingPosition';
import { useBibleData } from '~/composables/useBibleData';
import { useErrorHandler } from '~/composables/useErrorHandler';
import { useAuthService } from '~/composables/useAuthService';
import { useSelectedPlanStore } from '~/stores/selectedPlan';
import type { BiblePosition, RecentRecord, HomeStatsResponse, RecentRecordRaw } from '~/types/bible';

// Icons
import SettingsIcon from '~/components/icons/SettingsIcon.vue';
import ArrowRightIcon from '~/components/icons/ArrowRightIcon.vue';
import BookmarkIcon from '~/components/icons/BookmarkIcon.vue';
import DocumentIcon from '~/components/icons/DocumentIcon.vue';
import LayersIcon from '~/components/icons/LayersIcon.vue';
import HistoryIcon from '~/components/icons/HistoryIcon.vue';
import ListIcon from '~/components/icons/ListIcon.vue';
import ChevronRightIcon from '~/components/icons/ChevronRightIcon.vue';
import PlayIcon from '~/components/icons/PlayIcon.vue';
import CheckCircleIcon from '~/components/icons/CheckCircleIcon.vue';
import InfoIcon from '~/components/icons/InfoIcon.vue';
import CalendarIcon from '~/components/icons/CalendarIcon.vue';

const router = useRouter();
const api = useApi();
const { loadReadingPosition } = useReadingPosition();
const { getBookName, getChapterUnit } = useBibleData();
const { handleSilentError } = useErrorHandler();
const auth = useAuthService();
const selectedPlanStore = useSelectedPlanStore();

const emit = defineEmits<{
  (e: 'continue-reading'): void;
  (e: 'select-book', bookId: string, chapter: number): void;
  (e: 'show-toc'): void;
  (e: 'start-tongdok', schedule: TodaySchedule): void;
}>();

interface TodaySchedule {
  id: number;
  book_code: string;
  book_name: string;
  range: string;
  start_chapter: number;
  end_chapter: number;
  total: number;
  completed: number;
  isCompleted: boolean;
  plan_id: number;
}

const lastPosition = ref<BiblePosition | null>(null);
const bookmarkCount = ref(0);
const noteCount = ref(0);
const highlightCount = ref(0);
const recentRecords = ref<RecentRecord[]>([]);
const todaySchedule = ref<TodaySchedule | null>(null);
const hasPlan = ref(false);
const tipsDismissed = ref(false);

const isAuthenticated = computed(() => auth.isAuthenticated.value);

const hasBookmarks = computed(() => bookmarkCount.value > 0);
const hasNotes = computed(() => noteCount.value > 0);
const hasHighlights = computed(() => highlightCount.value > 0);

const showWelcomeGuide = computed(() =>
  !lastPosition.value && !todaySchedule.value && recentRecords.value.length === 0
);

const showUsageTips = computed(() => {
  if (tipsDismissed.value) return false;
  // 활동이 적을 때만 표시 (3개 미만의 활동)
  const totalActivity = bookmarkCount.value + noteCount.value + highlightCount.value;
  return totalActivity < 3 && (!hasBookmarks.value || !hasNotes.value || !hasHighlights.value);
});

const canDismissTips = computed(() => {
  // 최소 하나라도 활동이 있으면 숨기기 가능
  return bookmarkCount.value + noteCount.value + highlightCount.value > 0;
});

onMounted(async () => {
  // localStorage에서 팁 숨김 여부 확인
  if (typeof window !== 'undefined') {
    tipsDismissed.value = localStorage.getItem('bible_tips_dismissed') === 'true';
  }

  // 마지막 읽기 위치 로드
  const lastPos = await loadReadingPosition();
  if (lastPos) {
    lastPosition.value = {
      book: lastPos.book,
      chapter: lastPos.chapter,
      book_name: getBookName(lastPos.book)
    };
  }

  // 인증된 사용자: 오늘의 스케줄 및 통계 로드
  if (isAuthenticated.value) {
    await Promise.all([
      loadHomeStats(),
      loadTodaySchedule()
    ]);
  }
});

async function loadHomeStats() {
  try {
    const statsRes = await api.get('/api/v1/todos/bible/home-stats/');
    const data = statsRes.data as HomeStatsResponse | undefined;
    if (data) {
      bookmarkCount.value = data.bookmarks || 0;
      noteCount.value = data.notes || 0;
      highlightCount.value = data.highlights || 0;
      recentRecords.value = (data.recent_records || []).map((r: RecentRecordRaw) => ({
        ...r,
        book_name: getBookName(r.book)
      }));
    }
  } catch (error) {
    handleSilentError(error, '홈 데이터 로드');
  }
}

async function loadTodaySchedule() {
  const planId = selectedPlanStore.effectivePlanId;
  if (!planId) {
    hasPlan.value = false;
    return;
  }

  hasPlan.value = true;

  try {
    const response = await api.get(`/api/v1/todos/schedules/today/?plan_id=${planId}`);
    if (response.data.success && response.data.schedules && response.data.schedules.length > 0) {
      const schedules = response.data.schedules;
      const firstSchedule = schedules[0];
      const completedCount = schedules.filter((s: any) => s.is_completed).length;

      const unit = getChapterUnit(firstSchedule.book_code);
      let range = `${firstSchedule.start_chapter}${unit}`;
      if (firstSchedule.end_chapter && firstSchedule.end_chapter !== firstSchedule.start_chapter) {
        range = `${firstSchedule.start_chapter}-${firstSchedule.end_chapter}${unit}`;
      }

      todaySchedule.value = {
        id: firstSchedule.id,
        book_code: firstSchedule.book_code,
        book_name: getBookName(firstSchedule.book_code),
        range,
        start_chapter: firstSchedule.start_chapter,
        end_chapter: firstSchedule.end_chapter || firstSchedule.start_chapter,
        total: schedules.length,
        completed: completedCount,
        isCompleted: completedCount === schedules.length,
        plan_id: planId
      };
    }
  } catch (error) {
    handleSilentError(error, '오늘의 통독 로드');
  }
}

function startTodayTongdok() {
  if (!todaySchedule.value) return;

  // 통독 시작 이벤트 emit 또는 직접 네비게이션
  const { book_code, start_chapter, id, plan_id } = todaySchedule.value;
  router.push({
    path: '/bible',
    query: {
      book: book_code,
      chapter: start_chapter.toString(),
      tongdok: 'true',
      schedule: id.toString(),
      plan: plan_id.toString()
    }
  });
}

const handleRecordClick = (record: RecentRecord) => {
  emit('select-book', record.book, record.chapter);
};

const dismissTips = () => {
  tipsDismissed.value = true;
  if (typeof window !== 'undefined') {
    localStorage.setItem('bible_tips_dismissed', 'true');
  }
};

const formatDate = (dateStr: string) => {
  const date = new Date(dateStr);
  const today = new Date();
  const diff = Math.floor((today.getTime() - date.getTime()) / (1000 * 60 * 60 * 24));

  if (diff === 0) return '오늘';
  if (diff === 1) return '어제';
  if (diff < 7) return `${diff}일 전`;

  return date.toLocaleDateString('ko-KR', { month: 'short', day: 'numeric' });
};

const formatTodayDate = () => {
  const today = new Date();
  return today.toLocaleDateString('ko-KR', { month: 'long', day: 'numeric', weekday: 'short' });
};
</script>

<style scoped>
.bible-home {
  min-height: 100vh;
  min-height: 100dvh;
  background: var(--background-color);
}

.home-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem;
  background: var(--color-bg-card, #fff);
  border-bottom: 1px solid var(--color-border, #e5e7eb);
  position: sticky;
  top: 0;
  z-index: 10;
}

.home-header h1 {
  font-size: 1.25rem;
  font-weight: 700;
  color: var(--text-primary, #1f2937);
}

.settings-btn {
  padding: 0.5rem;
  color: var(--text-secondary, #6b7280);
  border-radius: 8px;
  transition: all 0.2s;
}

.settings-btn:hover {
  background: var(--color-bg-secondary, #f3f4f6);
  color: var(--text-primary, #1f2937);
}

.home-content {
  padding: 1rem;
  padding-bottom: 2rem;
}

/* 섹션 */
.section-title {
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-primary, #1f2937);
  margin-bottom: 0.75rem;
}

/* ========== 오늘의 통독 카드 ========== */
.today-tongdok-section {
  margin-bottom: 1.5rem;
}

.today-card {
  background: linear-gradient(135deg, var(--primary-color, #6366f1) 0%, #818cf8 100%);
  border-radius: 16px;
  padding: 1.25rem;
  color: white;
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
}

.today-card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 1rem;
}

.today-badge {
  background: rgba(255, 255, 255, 0.2);
  padding: 0.25rem 0.75rem;
  border-radius: 20px;
  font-size: 0.75rem;
  font-weight: 600;
}

.today-date {
  font-size: 0.8125rem;
  opacity: 0.9;
}

.today-card-body {
  margin-bottom: 1rem;
}

.today-schedule {
  display: flex;
  align-items: baseline;
  gap: 0.5rem;
  margin-bottom: 0.75rem;
}

.schedule-book {
  font-size: 1.25rem;
  font-weight: 700;
}

.schedule-range {
  font-size: 1rem;
  opacity: 0.9;
}

.today-progress {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.progress-label {
  font-size: 0.75rem;
  opacity: 0.9;
  white-space: nowrap;
}

.mini-progress-bar {
  flex: 1;
  height: 6px;
  background: rgba(255, 255, 255, 0.3);
  border-radius: 3px;
  overflow: hidden;
}

.mini-progress-fill {
  height: 100%;
  background: white;
  border-radius: 3px;
  transition: width 0.3s ease;
}

.today-start-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.875rem;
  background: white;
  color: var(--primary-color, #6366f1);
  border-radius: 12px;
  font-size: 0.9375rem;
  font-weight: 600;
  transition: all 0.2s;
}

.today-start-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.today-start-btn.is-completed {
  background: rgba(255, 255, 255, 0.2);
  color: white;
}

.no-plan-hint {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-top: 0.75rem;
  padding: 0.75rem;
  background: var(--color-bg-secondary, #f3f4f6);
  border-radius: 10px;
  font-size: 0.8125rem;
  color: var(--text-secondary, #6b7280);
}

.plan-link {
  color: var(--primary-color, #6366f1);
  font-weight: 500;
  margin-left: auto;
}

/* ========== 첫 방문자 가이드 ========== */
.welcome-section {
  margin-bottom: 1.5rem;
}

.welcome-card {
  background: var(--color-bg-card, #fff);
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 16px;
  padding: 2rem 1.5rem;
  text-align: center;
}

.welcome-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.welcome-card h2 {
  font-size: 1.125rem;
  font-weight: 700;
  color: var(--text-primary, #1f2937);
  margin-bottom: 0.5rem;
}

.welcome-card p {
  font-size: 0.9375rem;
  color: var(--text-secondary, #6b7280);
  margin-bottom: 1.5rem;
}

.welcome-actions {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.welcome-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.875rem 1rem;
  border-radius: 10px;
  font-size: 0.9375rem;
  font-weight: 500;
  transition: all 0.2s;
}

.welcome-btn.primary {
  background: var(--primary-color, #6366f1);
  color: white;
}

.welcome-btn.primary:hover {
  background: var(--primary-dark, #4f46e5);
}

.welcome-btn.secondary {
  background: var(--color-bg-secondary, #f3f4f6);
  color: var(--text-primary, #1f2937);
  border: 1px solid var(--color-border, #e5e7eb);
}

.welcome-btn.secondary:hover {
  background: var(--color-bg-tertiary, #e5e7eb);
}

/* ========== 기능 카드 (개선) ========== */
.features-section {
  margin-bottom: 1.5rem;
}

.feature-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.feature-card {
  display: flex;
  align-items: center;
  gap: 0.875rem;
  padding: 1rem;
  background: var(--color-bg-card, #fff);
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 12px;
  transition: all 0.2s;
}

.feature-card:hover {
  background: var(--color-bg-secondary, #f3f4f6);
  border-color: var(--color-border-hover, #d1d5db);
}

.feature-icon {
  width: 44px;
  height: 44px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 12px;
  flex-shrink: 0;
}

.feature-icon.bookmark {
  background: #fef3c7;
  color: #d97706;
}

.feature-icon.note {
  background: #dbeafe;
  color: #2563eb;
}

.feature-icon.highlight {
  background: #fce7f3;
  color: #db2777;
}

.feature-icon.history {
  background: #dcfce7;
  color: #16a34a;
}

.feature-content {
  flex: 1;
  text-align: left;
  min-width: 0;
}

.feature-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.125rem;
}

.feature-name {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--text-primary, #1f2937);
}

.feature-count {
  padding: 0.125rem 0.5rem;
  background: var(--primary-light, #eef2ff);
  color: var(--primary-color, #6366f1);
  font-size: 0.75rem;
  font-weight: 600;
  border-radius: 10px;
}

.feature-desc {
  font-size: 0.8125rem;
  color: var(--text-secondary, #6b7280);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.feature-arrow {
  color: var(--text-muted, #9ca3af);
  flex-shrink: 0;
}

/* ========== 사용 팁 ========== */
.tips-section {
  margin-bottom: 1.5rem;
  background: var(--color-bg-card, #fff);
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 12px;
  padding: 1rem;
}

.tips-section .section-title {
  margin-bottom: 0.75rem;
}

.tips-list {
  display: flex;
  flex-direction: column;
  gap: 0.875rem;
}

.tip-item {
  display: flex;
  gap: 0.75rem;
  padding: 0.75rem;
  background: var(--color-bg-secondary, #f9fafb);
  border-radius: 10px;
}

.tip-icon {
  font-size: 1.25rem;
  flex-shrink: 0;
}

.tip-content strong {
  display: block;
  font-size: 0.875rem;
  color: var(--text-primary, #1f2937);
  margin-bottom: 0.25rem;
}

.tip-content p {
  font-size: 0.8125rem;
  color: var(--text-secondary, #6b7280);
  line-height: 1.5;
}

.tip-content em {
  color: var(--primary-color, #6366f1);
  font-style: normal;
  font-weight: 500;
}

.dismiss-tips-btn {
  display: block;
  width: 100%;
  margin-top: 0.75rem;
  padding: 0.5rem;
  font-size: 0.75rem;
  color: var(--text-muted, #9ca3af);
  text-align: center;
  transition: color 0.2s;
}

.dismiss-tips-btn:hover {
  color: var(--text-secondary, #6b7280);
}

/* ========== 계속 읽기 ========== */
.continue-section {
  margin-bottom: 1.5rem;
}

.continue-card {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  padding: 1rem 1.25rem;
  background: var(--color-bg-card, #fff);
  border: 1px solid var(--color-border, #e5e7eb);
  color: var(--text-primary, #1f2937);
  border-radius: 12px;
  transition: all 0.2s;
}

.continue-card:hover {
  background: var(--color-bg-secondary, #f3f4f6);
  border-color: var(--primary-color, #6366f1);
}

.continue-info {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.continue-info .book-name {
  font-weight: 600;
  font-size: 1rem;
}

.continue-info .chapter {
  color: var(--text-secondary, #6b7280);
  font-size: 0.9375rem;
}

/* ========== 최근 읽은 기록 ========== */
.recent-section {
  margin-bottom: 1.5rem;
}

.recent-list {
  background: var(--color-bg-card, #fff);
  border-radius: 12px;
  border: 1px solid var(--color-border, #e5e7eb);
  overflow: hidden;
}

.recent-list li {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.875rem 1rem;
  cursor: pointer;
  transition: background 0.2s;
}

.recent-list li:not(:last-child) {
  border-bottom: 1px solid var(--color-border, #e5e7eb);
}

.recent-list li:hover {
  background: var(--color-bg-secondary, #f3f4f6);
}

.record-location {
  font-size: 0.9375rem;
  color: var(--text-primary, #1f2937);
}

.record-date {
  font-size: 0.75rem;
  color: var(--text-muted, #9ca3af);
}

/* ========== 목차 바로가기 ========== */
.toc-shortcut {
  margin-top: 1rem;
}

.toc-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  width: 100%;
  padding: 0.875rem;
  background: var(--color-bg-card, #fff);
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 12px;
  font-size: 0.9375rem;
  color: var(--text-primary, #1f2937);
  transition: all 0.2s;
}

.toc-btn:hover {
  background: var(--color-bg-secondary, #f3f4f6);
  border-color: var(--primary-color, #6366f1);
}

.toc-btn svg {
  color: var(--primary-color, #6366f1);
}

/* ========== 다크모드 ========== */
:root.dark .home-header {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .today-card {
  background: linear-gradient(135deg, #4f46e5 0%, #6366f1 100%);
}

:root.dark .no-plan-hint {
  background: var(--color-bg-tertiary);
}

:root.dark .welcome-card {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .feature-card {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .feature-card:hover {
  background: var(--color-bg-tertiary);
}

:root.dark .tips-section {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .tip-item {
  background: var(--color-bg-tertiary);
}

:root.dark .continue-card {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .continue-card:hover {
  background: var(--color-bg-tertiary);
}

:root.dark .recent-list {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .recent-list li:not(:last-child) {
  border-color: var(--color-border);
}

:root.dark .recent-list li:hover {
  background: var(--color-bg-tertiary);
}

:root.dark .toc-btn {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .toc-btn:hover {
  background: var(--color-bg-tertiary);
}

/* ========== 모바일 반응형 ========== */
@media (max-width: 400px) {
  .today-card {
    padding: 1rem;
  }

  .schedule-book {
    font-size: 1.125rem;
  }

  .welcome-card {
    padding: 1.5rem 1rem;
  }
}
</style>
