// maeil1dok-next/src/app/(public)/auth/forgot-password/page.tsx
'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function getEmailError(value: string): string {
  if (!value) return '이메일을 입력해주세요'
  if (!emailRegex.test(value)) return '올바른 이메일 형식이 아닙니다'
  return ''
}

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState('')
  const [emailTouched, setEmailTouched] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [isSubmitted, setIsSubmitted] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)

  const router = useRouter()
  const supabase = createClient()

  const normalizedEmail = email.trim()
  const emailError = useMemo(() => getEmailError(normalizedEmail), [normalizedEmail])
  const isFormValid = normalizedEmail.length > 0 && !emailError

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setEmailTouched(true)
    setSubmitError(null)

    if (!isFormValid) return

    setIsLoading(true)

    try {
      const { error } = await supabase.auth.resetPasswordForEmail(normalizedEmail, {
        redirectTo: `${window.location.origin}/auth/reset-password`,
      })

      if (error) throw error

      setIsSubmitted(true)
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : '재설정 메일 전송에 실패했습니다')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div
      className="min-h-screen flex items-center justify-center px-4 py-12"
      style={{ backgroundColor: 'var(--color-bg-base)' }}
    >
      <div className="w-full max-w-[28rem] flex flex-col gap-6 fade-in">
        <button
          type="button"
          onClick={() => router.back()}
          className="self-start flex items-center p-2 -m-2 transition-colors duration-200 hover:text-[var(--color-slate-800)]"
          style={{ color: 'var(--color-slate-500)' }}
          aria-label="뒤로 가기"
        >
          <svg aria-hidden="true" width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
        </button>

        <div className="text-center">
          <Image
            src="/images/로고_투명.png"
            alt="매일일독"
            width={160}
            height={32}
            className="h-8 w-auto mx-auto"
            priority
          />
        </div>

        {!isSubmitted ? (
          <>
            <div className="text-center flex flex-col gap-2">
              <h1 className="text-xl font-semibold m-0" style={{ color: 'var(--color-slate-800)' }}>
                비밀번호 재설정
              </h1>
              <p className="text-sm m-0 leading-relaxed" style={{ color: 'var(--color-slate-600)' }}>
                가입할 때 사용한 이메일을 입력하시면
                <br />
                비밀번호 재설정 링크를 보내드립니다.
              </p>
            </div>

            <form onSubmit={handleSubmit} className="flex flex-col gap-4">
              <div className="flex flex-col gap-1.5">
                <label htmlFor="email" className="text-sm font-medium" style={{ color: 'var(--color-slate-700)' }}>
                  이메일
                </label>
                <input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(event) => setEmail(event.target.value)}
                  onBlur={() => setEmailTouched(true)}
                  autoComplete="email"
                  placeholder="example@email.com"
                  className="appearance-none block w-full py-3 px-4 text-sm rounded-md transition-all duration-200"
                  style={{
                    backgroundColor: 'var(--color-bg-card)',
                    color: 'var(--color-slate-800)',
                    border: emailTouched && emailError
                      ? '1px solid #ef4444'
                      : '1px solid var(--color-slate-300)',
                  }}
                />
                {emailTouched && emailError && <p className="text-xs m-0" style={{ color: '#ef4444' }}>{emailError}</p>}
              </div>

              <button
                type="submit"
                disabled={isLoading || !isFormValid}
                className="w-full py-3 px-6 rounded-md text-sm font-medium border-none text-white transition-all duration-200"
                style={{
                  backgroundColor: 'var(--primary-color)',
                  cursor: isLoading || !isFormValid ? 'not-allowed' : 'pointer',
                  opacity: isLoading || !isFormValid ? 0.7 : 1,
                }}
              >
                {isLoading ? '전송 중...' : '재설정 링크 보내기'}
              </button>
            </form>

            <div className="text-center text-sm">
              <Link href="/login" className="hover:underline" style={{ color: 'var(--color-slate-600)' }}>
                로그인으로 돌아가기
              </Link>
            </div>
          </>
        ) : (
          <div
            className="p-6 rounded-xl text-center flex flex-col gap-3"
            style={{
              backgroundColor: 'var(--color-bg-card)',
              boxShadow: 'var(--shadow-sm)',
            }}
          >
            <h2 className="text-xl font-semibold m-0" style={{ color: 'var(--color-slate-800)' }}>
              이메일을 확인해주세요
            </h2>
            <p className="text-sm m-0 leading-relaxed" style={{ color: 'var(--color-slate-600)' }}>
              {normalizedEmail}로 비밀번호 재설정 링크를 보냈습니다.
              <br />
              이메일을 확인하여 비밀번호를 재설정해주세요.
            </p>
            <p className="text-xs m-0" style={{ color: 'var(--color-slate-500)' }}>
              이메일이 도착하지 않았다면 스팸 폴더를 확인해주세요.
            </p>
            <Link
              href="/login"
              className="w-full py-3 px-6 rounded-md text-sm font-medium border-none text-white transition-all duration-200"
              style={{
                backgroundColor: 'var(--primary-color)',
                display: 'inline-block',
              }}
            >
              로그인으로 이동
            </Link>
          </div>
        )}

        {submitError && (
          <div
            className="p-3 rounded-md text-sm"
            style={{
              backgroundColor: 'var(--color-danger-bg)',
              color: 'var(--color-danger-text)',
              border: '1px solid var(--color-danger)',
            }}
          >
            {submitError}
          </div>
        )}

        <div className="flex items-center justify-center gap-2 text-xs mt-2" style={{ color: 'var(--color-slate-400)' }}>
          <Link href="/terms" className="hover:underline" style={{ color: 'inherit' }}>
            이용약관
          </Link>
          <span style={{ color: 'var(--color-slate-300)' }}>|</span>
          <Link href="/privacy" className="hover:underline" style={{ color: 'inherit' }}>
            개인정보처리방침
          </Link>
          <span style={{ color: 'var(--color-slate-300)' }}>|</span>
          <Link href="/company" className="hover:underline" style={{ color: 'inherit' }}>
            사업자 정보
          </Link>
        </div>
      </div>
    </div>
  )
}

// frontend/app/pages/auth/forgot-password.vue
<template>
  <div class="forgot-container">
    <div class="forgot-box">
      <button @click="goBack" class="back-btn">
        <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
      </button>

      <div class="logo-container">
        <NuxtImg
          src="/images/logo-transparent.png"
          alt="매일일독"
          class="logo"
          loading="lazy"
          format="webp"
        />
      </div>

      <div v-if="!submitted" class="form-container">
        <h2 class="title">비밀번호 재설정</h2>
        <p class="description">
          가입할 때 사용한 이메일을 입력하시면<br>
          비밀번호 재설정 링크를 보내드립니다.
        </p>

        <form @submit.prevent="handleSubmit" class="forgot-form">
          <div class="input-group">
            <label for="email" class="visually-hidden">이메일</label>
            <input
              id="email"
              v-model="email"
              type="email"
              required
              autocomplete="email"
              class="form-input"
              placeholder="이메일"
            >
          </div>

          <button type="submit" class="submit-button" :disabled="loading">
            {{ loading ? '전송 중...' : '재설정 링크 보내기' }}
          </button>
        </form>

        <div class="login-section">
          <NuxtLink to="/login" class="login-link">
            로그인으로 돌아가기
          </NuxtLink>
        </div>
      </div>

      <div v-else class="success-container">
        <svg class="success-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
        <h2 class="success-title">이메일을 확인해주세요</h2>
        <p class="success-text">
          {{ email }}로 비밀번호 재설정 링크를 보냈습니다.<br>
          이메일을 확인하여 비밀번호를 재설정해주세요.
        </p>
        <p class="note-text">
          이메일이 도착하지 않았다면 스팸 폴더를 확인해주세요.
        </p>
        <button @click="goToLogin" class="action-button">
          로그인으로 이동
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useApi } from '~/composables/useApi'
import { useModal } from '~/composables/useModal'
import { useNavigation } from '~/composables/useNavigation'
import { useHead } from '#imports'

useHead({
  title: '비밀번호 재설정 - 매일일독',
  meta: [
    { name: 'robots', content: 'noindex' }
  ]
})

const router = useRouter()
const api = useApi()
const modal = useModal()
const { goBack: navGoBack } = useNavigation()

const email = ref('')
const loading = ref(false)
const submitted = ref(false)

const handleSubmit = async () => {
  loading.value = true
  try {
    await api.post('/api/v1/auth/request-password-reset/', { email: email.value })
    submitted.value = true
  } catch (error) {
    await modal.alert({
      title: '오류',
      description: '요청 처리 중 문제가 발생했습니다. 잠시 후 다시 시도해주세요.',
      icon: 'error'
    })
  } finally {
    loading.value = false
  }
}

const goBack = () => {
  navGoBack('/login')
}

const goToLogin = () => {
  router.push('/login')
}
</script>

<style scoped>
.forgot-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--color-bg-base);
  padding: 3rem 1rem;
}

.forgot-box {
  width: 100%;
  max-width: 28rem;
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.back-btn {
  display: flex;
  align-items: center;
  color: var(--color-slate-500);
  background: none;
  border: none;
  cursor: pointer;
  padding: 0.5rem;
  margin: -0.5rem;
  transition: color 0.2s ease;
  align-self: flex-start;
}

.back-btn:hover {
  color: var(--color-slate-800);
}

.logo-container {
  text-align: center;
  margin-bottom: 1rem;
}

.logo {
  height: 2rem;
  width: auto;
  object-fit: contain;
  margin: 0 auto;
}

[data-theme="dark"] .logo {
  filter: brightness(0) invert(1);
}

.form-container {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.title {
  font-size: 1.5rem;
  font-weight: 600;
  color: var(--color-slate-800);
  text-align: center;
  margin: 0;
}

.description {
  font-size: 0.875rem;
  color: var(--color-slate-600);
  text-align: center;
  line-height: 1.6;
  margin: 0;
}

.forgot-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.input-group {
  display: flex;
  flex-direction: column;
}

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

.form-input {
  appearance: none;
  display: block;
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid var(--color-slate-300);
  border-radius: 0.375rem;
  background-color: var(--color-bg-card);
  color: var(--color-slate-800);
  font-size: 0.875rem;
  transition: all 0.2s ease;
}

.form-input::placeholder {
  color: var(--color-slate-400);
}

.form-input:focus {
  outline: none;
  border-color: var(--color-accent-secondary);
  box-shadow: 0 0 0 3px var(--color-accent-bg);
}

.submit-button {
  width: 100%;
  padding: 0.75rem 1.5rem;
  background-color: var(--primary-color);
  color: white;
  border: none;
  border-radius: 0.375rem;
  font-weight: 500;
  font-size: 0.875rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.submit-button:hover:not(:disabled) {
  background-color: var(--primary-dark);
  transform: translateY(-1px);
}

.submit-button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.login-section {
  text-align: center;
}

.login-link {
  color: var(--color-slate-600);
  font-size: 0.875rem;
  text-decoration: none;
  transition: color 0.2s ease;
}

.login-link:hover {
  color: var(--primary-color);
}

.success-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  padding: 2rem;
  background-color: var(--color-bg-card);
  border-radius: 0.75rem;
  box-shadow: var(--shadow-sm);
  text-align: center;
}

.success-icon {
  width: 4rem;
  height: 4rem;
  color: var(--primary-color);
}

.success-title {
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--color-slate-800);
  margin: 0;
}

.success-text {
  font-size: 0.875rem;
  color: var(--color-slate-600);
  margin: 0;
  line-height: 1.6;
}

.note-text {
  font-size: 0.75rem;
  color: var(--color-slate-500);
  margin: 0;
}

.action-button {
  width: 100%;
  padding: 0.75rem 1.5rem;
  background-color: var(--primary-color);
  color: white;
  border: none;
  border-radius: 0.375rem;
  font-weight: 500;
  font-size: 0.875rem;
  cursor: pointer;
  transition: all 0.2s ease;
  margin-top: 0.5rem;
}

.action-button:hover {
  background-color: var(--primary-dark);
  transform: translateY(-1px);
}
</style>
