// maeil1dok-next/src/app/(public)/auth/verify-email/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

function getEmailError(value: string): string {
  if (!value) return '이메일을 입력해주세요'
  if (!emailRegex.test(value)) return '올바른 이메일 형식이 아닙니다'
  return ''
}

type VerifyStatus = 'pending' | 'success' | 'error'

export default function VerifyEmailPage() {
  const [email, setEmail] = useState('')
  const [emailTouched, setEmailTouched] = useState(false)
  const [status, setStatus] = useState<VerifyStatus>('pending')
  const [isLoading, setIsLoading] = useState(false)
  const [message, setMessage] = useState('인증 메일을 확인해주세요. 인증 링크를 눌러야 가입이 완료됩니다.')

  const router = useRouter()
  const supabase = createClient()

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const initialEmail = params.get('email') ?? ''
    const statusParam = params.get('status')

    setEmail(initialEmail)

    if (statusParam === 'success') {
      setStatus('success')
      setMessage('이메일 인증이 완료되었습니다. 이제 로그인하여 서비스를 이용할 수 있습니다.')
      return
    }

    if (statusParam === 'error') {
      setStatus('error')
      setMessage('인증 링크가 만료되었거나 유효하지 않습니다.')
      return
    }

    setStatus('pending')
    setMessage('인증 메일을 확인해주세요. 인증 링크를 눌러야 가입이 완료됩니다.')
  }, [])

  const normalizedEmail = email.trim()
  const emailError = useMemo(() => getEmailError(normalizedEmail), [normalizedEmail])
  const canResend = normalizedEmail.length > 0 && !emailError

  async function handleResend() {
    setEmailTouched(true)
    if (!canResend) return

    setIsLoading(true)

    try {
      const { error } = await supabase.auth.resend({
        type: 'signup',
        email: normalizedEmail,
      })

      if (error) throw error

      setStatus('pending')
      setMessage('인증 메일을 재발송했습니다. 이메일을 확인해주세요.')
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : '인증 메일 재발송에 실패했습니다')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div
      className="min-h-screen flex items-center justify-center px-4 py-12"
      style={{ backgroundColor: 'var(--color-bg-base)' }}
    >
      <div className="w-full max-w-[28rem] flex flex-col gap-6 fade-in">
        <button
          type="button"
          onClick={() => router.back()}
          className="self-start flex items-center p-2 -m-2 transition-colors duration-200 hover:text-[var(--color-slate-800)]"
          style={{ color: 'var(--color-slate-500)' }}
          aria-label="뒤로 가기"
        >
          <svg aria-hidden="true" width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
        </button>

        <div className="text-center">
          <Image
            src="/images/로고_투명.png"
            alt="매일일독"
            width={160}
            height={32}
            className="h-8 w-auto mx-auto"
            priority
          />
        </div>

        <div
          className="p-6 rounded-xl text-center flex flex-col gap-4"
          style={{
            backgroundColor: 'var(--color-bg-card)',
            boxShadow: 'var(--shadow-sm)',
          }}
        >
          <h1 className="text-xl font-semibold m-0" style={{ color: 'var(--color-slate-800)' }}>
            {status === 'success' ? '이메일 인증 완료!' : '이메일 인증 확인'}
          </h1>

          <p
            className="text-sm m-0 leading-relaxed"
            style={{
              color: status === 'error' ? 'var(--color-danger-text)' : 'var(--color-slate-600)',
            }}
          >
            {message}
          </p>

          {status !== 'success' && (
            <div className="flex flex-col gap-2 text-left">
              <label htmlFor="verify-email" className="text-sm font-medium" style={{ color: 'var(--color-slate-700)' }}>
                이메일
              </label>
              <input
                id="verify-email"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
                onBlur={() => setEmailTouched(true)}
                autoComplete="email"
                placeholder="example@email.com"
                className="appearance-none block w-full py-3 px-4 text-sm rounded-md transition-all duration-200"
                style={{
                  backgroundColor: 'var(--color-bg-card)',
                  color: 'var(--color-slate-800)',
                  border: emailTouched && emailError
                    ? '1px solid #ef4444'
                    : '1px solid var(--color-slate-300)',
                }}
              />
              {emailTouched && emailError && <p className="text-xs m-0" style={{ color: '#ef4444' }}>{emailError}</p>}
            </div>
          )}

          {status === 'success' ? (
            <button
              type="button"
              onClick={() => router.push('/login')}
              className="w-full py-3 px-6 rounded-md text-sm font-medium border-none text-white transition-all duration-200"
              style={{ backgroundColor: 'var(--primary-color)' }}
            >
              로그인으로 이동
            </button>
          ) : (
            <button
              type="button"
              onClick={handleResend}
              disabled={isLoading || !canResend}
              className="w-full py-3 px-6 rounded-md text-sm font-medium border-none text-white transition-all duration-200"
              style={{
                backgroundColor: 'var(--primary-color)',
                cursor: isLoading || !canResend ? 'not-allowed' : 'pointer',
                opacity: isLoading || !canResend ? 0.7 : 1,
              }}
            >
              {isLoading ? '발송 중...' : '인증 메일 재발송'}
            </button>
          )}
        </div>

        <div className="text-center text-sm">
          <Link href="/login" className="hover:underline" style={{ color: 'var(--color-slate-600)' }}>
            로그인으로 돌아가기
          </Link>
        </div>

        <div className="flex items-center justify-center gap-2 text-xs mt-2" style={{ color: 'var(--color-slate-400)' }}>
          <Link href="/terms" className="hover:underline" style={{ color: 'inherit' }}>
            이용약관
          </Link>
          <span style={{ color: 'var(--color-slate-300)' }}>|</span>
          <Link href="/privacy" className="hover:underline" style={{ color: 'inherit' }}>
            개인정보처리방침
          </Link>
          <span style={{ color: 'var(--color-slate-300)' }}>|</span>
          <Link href="/company" className="hover:underline" style={{ color: 'inherit' }}>
            사업자 정보
          </Link>
        </div>
      </div>
    </div>
  )
}

// frontend/app/pages/auth/verify-email.vue
<template>
  <div class="verify-container">
    <div class="verify-box">
      <div class="logo-container">
        <NuxtImg
          src="/images/logo-transparent.png"
          alt="매일일독"
          class="logo"
          loading="eager"
          format="webp"
        />
      </div>

      <div v-if="loading" class="status-container">
        <div class="spinner"></div>
        <p class="status-text">이메일 인증 중...</p>
      </div>

      <div v-else-if="success" class="status-container success">
        <svg class="status-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h2 class="status-title">이메일 인증 완료!</h2>
        <p class="status-text">{{ successMessage }}</p>
        <button @click="goToHome" class="action-button">
          시작하기
        </button>
      </div>

      <div v-else class="status-container error">
        <svg class="status-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h2 class="status-title">인증 실패</h2>
        <p class="status-text">{{ errorMessage }}</p>
        <div class="action-buttons">
          <button @click="resendEmail" class="action-button secondary" :disabled="resending">
            {{ resending ? '발송 중...' : '인증 메일 재발송' }}
          </button>
          <button @click="goToLogin" class="action-button">
            로그인으로 이동
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthService } from '~/composables/useAuthService'
import { useApi } from '~/composables/useApi'
import { useHead } from '#imports'

useHead({
  title: '이메일 인증 - 매일일독',
  meta: [
    { name: 'robots', content: 'noindex' }
  ]
})

const route = useRoute()
const router = useRouter()
const auth = useAuthService()
const api = useApi()

const loading = ref(true)
const success = ref(false)
const successMessage = ref('')
const errorMessage = ref('')
const resending = ref(false)
const userEmail = ref('')

onMounted(async () => {
  const token = route.query.token
  
  if (!token) {
    loading.value = false
    errorMessage.value = '인증 토큰이 없습니다.'
    return
  }

  try {
    const response = await api.POST('/api/v1/auth/verify-email/', { token })
    const data = response
    
    if (data.success) {
      success.value = true
      successMessage.value = '이메일 인증이 완료되었습니다. 이제 매일일독의 모든 기능을 사용할 수 있습니다.'
      
      if (data.access) {
        auth.setTokens(data.access, data.refresh)
        await auth.fetchUser()
      }
    }
  } catch (error) {
    const errorData = error.response?.data || {}
    errorMessage.value = errorData.error || '인증 처리 중 오류가 발생했습니다.'
  } finally {
    loading.value = false
  }
})

const resendEmail = async () => {
  if (!userEmail.value) {
    router.push('/login')
    return
  }
  
  resending.value = true
  try {
    await api.POST('/api/v1/auth/send-verification/', { email: userEmail.value })
    errorMessage.value = '인증 메일이 재발송되었습니다. 이메일을 확인해주세요.'
  } catch (error) {
    const errorData = error.response?.data || {}
    errorMessage.value = errorData.error || '메일 발송에 실패했습니다.'
  } finally {
    resending.value = false
  }
}

const goToHome = () => {
  router.push('/')
}

const goToLogin = () => {
  router.push('/login')
}
</script>

<style scoped>
.verify-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--color-bg-base);
  padding: 2rem 1rem;
}

.verify-box {
  width: 100%;
  max-width: 28rem;
  display: flex;
  flex-direction: column;
  gap: 2rem;
  text-align: center;
}

.logo-container {
  text-align: center;
  margin-bottom: 1rem;
}

.logo {
  height: 2rem;
  width: auto;
  object-fit: contain;
  margin: 0 auto;
}

[data-theme="dark"] .logo {
  filter: brightness(0) invert(1);
}

.status-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  padding: 2rem;
  background-color: var(--color-bg-card);
  border-radius: 0.75rem;
  box-shadow: var(--shadow-sm);
}

.spinner {
  width: 3rem;
  height: 3rem;
  border: 3px solid var(--color-slate-200);
  border-top-color: var(--primary-color);
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.status-icon {
  width: 4rem;
  height: 4rem;
}

.success .status-icon {
  color: #10B981;
}

.error .status-icon {
  color: #EF4444;
}

.status-title {
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--color-slate-800);
  margin: 0;
}

.status-text {
  font-size: 0.875rem;
  color: var(--color-slate-600);
  margin: 0;
  line-height: 1.5;
}

.action-buttons {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  width: 100%;
  margin-top: 0.5rem;
}

.action-button {
  width: 100%;
  padding: 0.75rem 1.5rem;
  background-color: var(--primary-color);
  color: white;
  border: none;
  border-radius: 0.375rem;
  font-weight: 500;
  font-size: 0.875rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.action-button:hover:not(:disabled) {
  background-color: var(--primary-dark);
  transform: translateY(-1px);
}

.action-button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.action-button.secondary {
  background-color: var(--color-bg-base);
  color: var(--color-slate-700);
  border: 1px solid var(--color-slate-300);
}

.action-button.secondary:hover:not(:disabled) {
  background-color: var(--color-slate-100);
}
</style>
