// maeil1dok-next/src/app/(authenticated)/bible/notes/[id]/page.tsx
'use client'

import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { BookOpen, ChevronLeft, ChevronRight, Loader2, Trash2 } from 'lucide-react'
import { useModal } from '@/hooks/useModal'
import { BIBLE_BOOKS } from '@/lib/bible/books'

interface Note {
  id: string
  user_id?: string
  book: string
  book_name?: string | null
  chapter: number
  start_verse?: number | null
  end_verse?: number | null
  content: string
  is_private: boolean
  created_at: string
  updated_at: string
}

export default function NoteDetailPage() {
  const params = useParams()
  const router = useRouter()
  const modal = useModal()
  const id = params && typeof params.id === 'string' ? params.id : ''

  const [note, setNote] = useState<Note | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [editContent, setEditContent] = useState('')
  const [isPrivate, setIsPrivate] = useState(true)
  const [originalContent, setOriginalContent] = useState('')
  const [originalPrivate, setOriginalPrivate] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement | null>(null)
  const saveTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    if (!id) return

    fetch(`/api/bible/notes/${id}`)
      .then(async (response) => {
        if (!response.ok) {
          throw new Error('failed to fetch note')
        }

        return response.json() as Promise<{ data?: Note }>
      })
      .then((json: { data?: Note }) => {
        const loadedNote = json.data ?? null
        setNote(loadedNote)
        setEditContent(loadedNote?.content ?? '')
        setIsPrivate(loadedNote?.is_private ?? true)
        setOriginalContent(loadedNote?.content ?? '')
        setOriginalPrivate(loadedNote?.is_private ?? true)
      })
      .catch(() => setNote(null))
      .finally(() => setIsLoading(false))
  }, [id])

  const hasChanges = useMemo(
    () => editContent !== originalContent || isPrivate !== originalPrivate,
    [editContent, isPrivate, originalContent, originalPrivate],
  )

  const formatDate = useCallback((value: string) => {
    const date = new Date(value)
    return date.toLocaleDateString('ko-KR', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }, [])

  const handleSave = useCallback(async () => {
    if (!note || !hasChanges || isSaving) return

    setIsSaving(true)

    const res = await fetch(`/api/bible/notes/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: editContent, is_private: isPrivate }),
    })

    if (res.ok) {
      const json = (await res.json()) as { data?: Note }
      const updated = json.data
      if (updated) {
        setNote(updated)
        setEditContent(updated.content)
        setIsPrivate(updated.is_private)
        setOriginalContent(updated.content)
        setOriginalPrivate(updated.is_private)
      } else {
        const updatedAt = new Date().toISOString()
        setNote((prev) => (prev ? { ...prev, content: editContent, is_private: isPrivate, updated_at: updatedAt } : prev))
        setOriginalContent(editContent)
        setOriginalPrivate(isPrivate)
      }
    }

    setIsSaving(false)
  }, [editContent, hasChanges, id, isPrivate, isSaving, note])

  const handleContentChange = useCallback((event: ChangeEvent<HTMLTextAreaElement>) => {
    setEditContent(event.target.value)
    event.target.style.height = 'auto'
    event.target.style.height = `${event.target.scrollHeight}px`
  }, [])

  async function handleDelete() {
    const confirmed = await modal.confirm({
      title: '묵상노트 삭제',
      description: '묵상노트를 삭제하시겠습니까?',
      confirmText: '삭제',
      cancelText: '취소',
      confirmVariant: 'danger',
      icon: 'warning',
    })

    if (!confirmed) return

    await fetch(`/api/bible/notes/${id}`, { method: 'DELETE' })
    router.push('/bible/notes')
  }

  async function handleBack() {
    if (!hasChanges) {
      router.back()
      return
    }

    const confirmed = await modal.confirm({
      title: '변경사항 저장 안 됨',
      description: '저장하지 않은 변경사항이 있습니다. 나가시겠습니까?',
      confirmText: '나가기',
      cancelText: '취소',
      confirmVariant: 'danger',
      icon: 'warning',
    })

    if (confirmed) {
      router.back()
    }
  }

  useEffect(() => {
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current)
      saveTimeoutRef.current = null
    }

    if (!hasChanges || isSaving) {
      return
    }

    saveTimeoutRef.current = setTimeout(() => {
      void handleSave()
    }, 3000)

    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current)
        saveTimeoutRef.current = null
      }
    }
  }, [handleSave, hasChanges, isSaving])

  function goToBible() {
    if (!note) return
    router.push(`/bible?book=${note.book}&chapter=${note.chapter}`)
  }

  if (isLoading) {
    return (
      <main className="flex min-h-dvh flex-col items-center justify-center gap-3 bg-[var(--color-bg-primary)] text-[var(--color-text-secondary)]">
        <Loader2 size={28} className="animate-spin" aria-hidden="true" />
        <p className="text-sm">묵상노트를 불러오는 중...</p>
      </main>
    )
  }

  if (!note) {
    return (
      <main className="flex min-h-dvh items-center justify-center bg-[var(--color-bg-primary)] px-6">
        <div className="text-center">
          <p className="text-sm text-[var(--color-text-secondary)]">묵상노트를 찾을 수 없습니다</p>
          <Link href="/bible/notes" className="mt-2 block text-sm text-[var(--color-accent-primary)]">목록으로 돌아가기</Link>
        </div>
      </main>
    )
  }

  return (
    <main className="min-h-dvh bg-[var(--color-bg-primary)] pb-24">
      <div className="mx-auto min-h-dvh max-w-[768px] bg-[var(--color-bg-primary)]">
        <header className="sticky top-0 z-20 border-b border-[var(--color-border)] bg-[var(--color-bg-card)]">
          <div className="flex items-center gap-3 px-4 py-3">
            <button
              type="button"
              className="-m-2 rounded-lg p-2 text-[var(--color-text-primary)] transition-colors hover:bg-[var(--color-bg-hover)]"
              onClick={() => void handleBack()}
              aria-label="뒤로 가기"
            >
              <ChevronLeft size={20} aria-hidden="true" />
            </button>
            <h1 className="flex-1 text-lg font-semibold text-[var(--color-text-primary)]">묵상노트</h1>
            <button
              type="button"
              className="-m-1 rounded-lg p-2 text-[var(--color-text-secondary)] transition-colors hover:bg-[var(--color-bg-hover)] hover:text-red-500"
              onClick={() => void handleDelete()}
              aria-label="묵상노트 삭제"
            >
              <Trash2 size={18} aria-hidden="true" />
            </button>
          </div>
        </header>

        <section className="flex min-h-[calc(100dvh-80px)] flex-col px-4 py-4">
          <button
            type="button"
            onClick={goToBible}
            className="mb-4 flex items-center gap-2 rounded-xl bg-[var(--color-bg-card)] px-3 py-3 text-[0.9375rem] font-medium text-[var(--color-accent-primary)] transition-colors hover:bg-[var(--color-bg-hover)]"
          >
            <BookOpen size={16} aria-hidden="true" />
            <span>{note.book_name || BIBLE_BOOKS[note.book]?.ko || note.book} {note.chapter}장</span>
            <ChevronRight size={14} className="ml-auto text-[var(--color-text-muted)]" aria-hidden="true" />
          </button>

          <div className="flex flex-1 flex-col rounded-2xl border border-[var(--color-border)] bg-[var(--color-bg-card)] p-4">
            <textarea
              ref={textareaRef}
              value={editContent}
              onChange={handleContentChange}
              placeholder="묵상 내용을 적어보세요..."
              className="min-h-[300px] w-full flex-1 resize-none border-none bg-transparent text-base leading-7 text-[var(--color-text-primary)] outline-none"
            />

            <div className="mt-4 flex items-center justify-between gap-3">
              <label className="inline-flex cursor-pointer items-center gap-2">
                <input
                  type="checkbox"
                  checked={isPrivate}
                  onChange={(event) => setIsPrivate(event.target.checked)}
                  className="peer sr-only"
                />
                <span className="relative h-7 w-12 rounded-full bg-[var(--color-border)] transition-colors peer-checked:bg-[var(--color-accent-primary)]">
                  <span className="absolute left-[3px] top-[3px] h-[22px] w-[22px] rounded-full bg-[var(--color-bg-card)] shadow-[var(--shadow-sm)] transition-transform peer-checked:translate-x-5" />
                </span>
                <span className="text-sm text-[var(--color-text-secondary)]">비공개</span>
              </label>
              <span className="text-xs text-[var(--color-text-muted)]">{formatDate(note.updated_at)} 수정됨</span>
            </div>

            <div className="mt-6 flex justify-end">
              <button
                type="button"
                onClick={() => void handleSave()}
                disabled={!hasChanges || isSaving}
                className="inline-flex min-w-[104px] items-center justify-center gap-2 rounded-[10px] bg-[var(--color-accent-primary)] px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-[var(--color-accent-hover)] disabled:cursor-not-allowed disabled:opacity-60"
              >
                {isSaving ? <Loader2 size={16} className="animate-spin" aria-hidden="true" /> : null}
                <span>{hasChanges ? '저장' : '저장됨'}</span>
              </button>
            </div>
          </div>
        </section>
      </div>
    </main>
  )
}

// frontend/app/pages/bible/notes/[id].vue
<template>
  <div class="bible-page note-detail-page">
    <header class="bible-page-header">
      <button class="bible-back-btn" @click="handleBack">
        <ChevronLeftIcon :size="20" />
      </button>
      <h1>묵상노트</h1>
      <button v-if="note" class="bible-header-btn danger" @click="handleDelete" title="삭제">
        <TrashIcon :size="20" />
      </button>
    </header>

    <!-- 로딩 -->
    <template v-if="isLoading">
      <SkeletonCard>
        <template #body>
          <SkeletonText :lines="12" lastLineWidth="60%" />
        </template>
      </SkeletonCard>
    </template>

    <!-- 노트 없음 -->
    <EmptyState v-else-if="!note" text="묵상노트를 찾을 수 없습니다">
      <template #action>
        <NuxtLink to="/bible/notes" class="back-link">목록으로 돌아가기</NuxtLink>
      </template>
    </EmptyState>

    <!-- 에디터 -->
    <div v-else class="note-editor">
      <div class="note-location" @click="goToBible">
        <BookIcon :size="16" />
        <span>{{ note.book_name || getBookName(note.book) }} {{ note.chapter }}장</span>
        <ChevronRightIcon :size="14" />
      </div>

      <textarea
        ref="textareaRef"
        v-model="editContent"
        placeholder="묵상 내용을 적어보세요..."
        class="content-editor"
      />

      <div class="note-options">
        <label class="private-toggle">
          <input type="checkbox" v-model="isPrivate" />
          <span class="toggle-slider"></span>
          <span class="toggle-label">비공개</span>
        </label>
        <span class="last-updated">{{ formatDate(note.updated_at) }} 수정됨</span>
      </div>

      <div class="action-bar">
        <button
          class="save-btn"
          @click="handleSave"
          :disabled="!hasChanges || isSaving"
        >
          <span v-if="isSaving" class="loading-spinner-small"></span>
          <span v-else>{{ hasChanges ? '저장' : '저장됨' }}</span>
        </button>
      </div>
    </div>

    <Toast />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useNote } from '~/composables/useNote';
import { useBibleData } from '~/composables/useBibleData';
import { useErrorHandler } from '~/composables/useErrorHandler';
import { useModal } from '~/composables/useModal';
import { TIMING, TOGGLE_SIZE } from '~/constants/bible';
import Toast from '~/components/Toast.vue';
import SkeletonCard from '~/components/ui/skeleton/SkeletonCard.vue';
import SkeletonText from '~/components/ui/skeleton/SkeletonText.vue';

definePageMeta({
  layout: 'default'
});

const route = useRoute();
const router = useRouter();
const { handleApiError } = useErrorHandler();
const modal = useModal();
const { currentNote: note, isNoteLoading: isLoading, fetchNote, updateNote, deleteNote } = useNote();
const { getBookName } = useBibleData();

const textareaRef = ref<HTMLTextAreaElement | null>(null);
const editContent = ref('');
const isPrivate = ref(true);
const isSaving = ref(false);
const originalContent = ref('');
const originalPrivate = ref(true);

const noteId = computed(() => parseInt(route.params.id as string));

onMounted(async () => {
  const loaded = await fetchNote(noteId.value);
  if (loaded) {
    editContent.value = loaded.content;
    isPrivate.value = loaded.is_private;
    originalContent.value = loaded.content;
    originalPrivate.value = loaded.is_private;
  }
});

const hasChanges = computed(() => {
  return editContent.value !== originalContent.value ||
         isPrivate.value !== originalPrivate.value;
});

const handleSave = async () => {
  if (!hasChanges.value) return;

  isSaving.value = true;
  try {
    await updateNote(noteId.value, {
      content: editContent.value,
      is_private: isPrivate.value
    });
    originalContent.value = editContent.value;
    originalPrivate.value = isPrivate.value;
  } catch (error) {
    handleApiError(error, '묵상노트 저장');
  } finally {
    isSaving.value = false;
  }
};

const handleDelete = async () => {
  const confirmed = await modal.confirm({
    title: '묵상노트 삭제',
    description: '묵상노트를 삭제하시겠습니까?',
    confirmText: '삭제',
    cancelText: '취소',
    confirmVariant: 'danger',
    icon: 'warning'
  });
  if (!confirmed) return;

  try {
    await deleteNote(noteId.value);
    router.push('/bible/notes');
  } catch (error) {
    handleApiError(error, '묵상노트 삭제');
  }
};

const handleBack = async () => {
  if (hasChanges.value) {
    const confirmed = await modal.confirm({
      title: '변경사항 저장 안 됨',
      description: '저장하지 않은 변경사항이 있습니다. 나가시겠습니까?',
      confirmText: '나가기',
      cancelText: '취소',
      confirmVariant: 'danger',
      icon: 'warning'
    });
    if (confirmed) {
      router.back();
    }
  } else {
    router.back();
  }
};

const goToBible = () => {
  if (note.value) {
    router.push({
      path: '/bible',
      query: {
        book: note.value.book,
        chapter: String(note.value.chapter)
      }
    });
  }
};

const formatDate = (dateStr: string): string => {
  const date = new Date(dateStr);
  return date.toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

// 자동 저장 (디바운스)
let saveTimeout: ReturnType<typeof setTimeout> | null = null;
watch([editContent, isPrivate], () => {
  if (saveTimeout) clearTimeout(saveTimeout);
  if (hasChanges.value && !isSaving.value) {
    saveTimeout = setTimeout(async () => {
      await handleSave();
    }, TIMING.AUTO_SAVE_DEBOUNCE);
  }
});
</script>

<style scoped>
/*
 * Note Detail Page specific styles
 * 공통 스타일은 bible-page.css에서 관리됨
 */

.note-detail-page {
  display: flex;
  flex-direction: column;
}

/* 로딩/빈 상태가 flex: 1을 차지하도록 */
.note-detail-page :deep(.loading-spinner-container),
.note-detail-page :deep(.empty-state-container) {
  flex: 1;
  min-height: auto;
}

.back-link {
  margin-top: 1rem;
  color: var(--primary-color, #6366f1);
  font-size: 0.875rem;
  text-decoration: none;
}

.back-link:hover {
  text-decoration: underline;
}

/* 에디터 */
.note-editor {
  flex: 1;
  display: flex;
  flex-direction: column;
  padding: 1rem;
}

.note-location {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem;
  background: var(--color-bg-card, #fff);
  border-radius: 8px;
  margin-bottom: 1rem;
  color: var(--primary-color, #6366f1);
  font-size: 0.9375rem;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.note-location:hover {
  background: var(--color-bg-hover, #f3f4f6);
}

.note-location svg:last-child {
  margin-left: auto;
  opacity: 0.5;
}

.content-editor {
  flex: 1;
  width: 100%;
  min-height: 300px;
  padding: 1rem;
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 12px;
  font-size: 1rem;
  color: var(--text-primary, #1f2937);
  background: var(--color-bg-card, #fff);
  resize: none;
  font-family: inherit;
  line-height: 1.75;
}

.content-editor:focus {
  outline: none;
  border-color: var(--primary-color, #6366f1);
  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1);
}

.note-options {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 1rem;
  padding: 0 0.25rem;
}

.private-toggle {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  cursor: pointer;
}

.private-toggle input {
  display: none;
}

.toggle-slider {
  width: 48px;
  height: 28px;
  background: var(--color-border, #e5e7eb);
  border-radius: 14px;
  position: relative;
  transition: background 0.2s;
}

.toggle-slider::after {
  content: '';
  position: absolute;
  top: 3px;
  left: 3px;
  width: 22px;
  height: 22px;
  background: white;
  border-radius: 50%;
  transition: transform 0.2s;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.private-toggle input:checked + .toggle-slider {
  background: var(--primary-color, #6366f1);
}

.private-toggle input:checked + .toggle-slider::after {
  transform: translateX(20px);
}

.toggle-label {
  font-size: 0.875rem;
  color: var(--text-secondary, #6b7280);
}

.last-updated {
  font-size: 0.75rem;
  color: var(--text-muted, #9ca3af);
}

.action-bar {
  margin-top: 1.5rem;
  display: flex;
  justify-content: flex-end;
}

.save-btn {
  padding: 0.75rem 1.5rem;
  background: var(--primary-color, #6366f1);
  color: white;
  border: none;
  border-radius: 10px;
  font-size: 0.9375rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  min-width: 100px;
  justify-content: center;
}

.save-btn:hover:not(:disabled) {
  background: var(--primary-dark, #4f46e5);
}

.save-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.loading-spinner-small {
  width: 16px;
  height: 16px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-top-color: white;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

/* 다크모드 */
:root.dark .note-location {
  background: var(--color-bg-card);
}

:root.dark .note-location:hover {
  background: var(--color-bg-hover);
}

:root.dark .content-editor {
  background: var(--color-bg-card);
  border-color: var(--color-border);
  color: var(--text-primary);
}

:root.dark .toggle-slider {
  background: var(--color-border);
}
</style>
