// maeil1dok-next/src/app/(authenticated)/bible/notes/page.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { FileText as DocumentIcon, Lock } from 'lucide-react'
import { BIBLE_BOOKS, BIBLE_BOOK_ORDER } from '@/lib/bible/books'
import { BibleSubpageLayout } from '../_shared/BibleSubpageLayout'
import { BibleSubpageTabs } from '../_shared/BibleSubpageTabs'
import { formatRelativeDate, truncate } from '../_shared/utils'

interface Note {
  id: string
  user_id?: string
  book: string
  book_name?: string | null
  chapter: number
  start_verse?: number | null
  end_verse?: number | null
  content: string
  is_private: boolean
  created_at: string
  updated_at: string
}

const OT_BOOK_KEYS = BIBLE_BOOK_ORDER.slice(0, 39)
const NT_BOOK_KEYS = BIBLE_BOOK_ORDER.slice(39)

export default function NotesPage() {
  const [notes, setNotes] = useState<Note[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [isAuthenticated, setIsAuthenticated] = useState(true)
  const [bookFilter, setBookFilter] = useState('')

  useEffect(() => {
    fetch('/api/bible/notes')
      .then(async (response) => {
        if (response.status === 401) {
          setIsAuthenticated(false)
          return { data: [] }
        }
        if (!response.ok) throw new Error('failed to fetch notes')
        return response.json() as Promise<{ data?: Note[] }>
      })
      .then((json: { data?: Note[] }) => setNotes(json.data ?? []))
      .catch(() => setNotes([]))
      .finally(() => setIsLoading(false))
  }, [])

  const bookOptions = useMemo(
    () => ({
      old: OT_BOOK_KEYS.map((book) => ({ key: book, name: BIBLE_BOOKS[book]?.ko ?? book })),
      newer: NT_BOOK_KEYS.map((book) => ({ key: book, name: BIBLE_BOOKS[book]?.ko ?? book })),
    }),
    [],
  )

  const filteredNotes = useMemo(() => {
    if (!bookFilter) return notes
    return notes.filter((note) => note.book === bookFilter)
  }, [bookFilter, notes])

  const isEmpty = !isAuthenticated || filteredNotes.length === 0
  const hasBookFilter = bookFilter !== ''
  const emptyText = !isAuthenticated
    ? '로그인 후 묵상노트를 확인할 수 있습니다'
    : hasBookFilter
      ? '해당 책에 작성된 묵상노트가 없습니다'
      : '작성된 묵상노트가 없습니다'
  const emptyHint = isAuthenticated && !hasBookFilter ? '말씀을 읽고 묵상을 기록해보세요' : undefined
  const emptyGuide = isAuthenticated && !hasBookFilter
    ? ['성경 읽기 화면으로 이동하세요', '상단 메뉴(⋮)를 탭하세요', '묵상노트 버튼을 선택하세요']
    : undefined

  const filterBar = isAuthenticated ? (
    <div className="px-4 py-3">
      <select
        value={bookFilter}
        onChange={(event) => setBookFilter(event.target.value)}
        className="h-10 w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-card)] px-3 text-sm text-[var(--color-text-primary)] outline-none transition-colors focus:border-[var(--color-accent-primary)]"
        aria-label="성경 권 필터"
      >
        <option value="">전체</option>
        <optgroup label="구약">
          {bookOptions.old.map((book) => (
            <option key={book.key} value={book.key}>{book.name}</option>
          ))}
        </optgroup>
        <optgroup label="신약">
          {bookOptions.newer.map((book) => (
            <option key={book.key} value={book.key}>{book.name}</option>
          ))}
        </optgroup>
      </select>
    </div>
  ) : null

  const tabs = useMemo(() => <BibleSubpageTabs current="notes" />, [])

  return (
    <BibleSubpageLayout
      title="묵상노트"
      loading={isLoading}
      loadingText="묵상노트를 불러오는 중..."
      empty={isEmpty}
      emptyText={emptyText}
      emptyHint={emptyHint}
      emptyGuide={emptyGuide}
      emptyIcon={<DocumentIcon size={48} aria-hidden="true" />}
      emptyAction={
        isAuthenticated ? null : (
          <Link
            href="/login"
            className="inline-flex rounded-lg bg-[var(--color-accent-primary)] px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--color-accent-hover)]"
          >
            로그인
          </Link>
        )
      }
      tabs={tabs}
      filter={filterBar}
    >
      <ul className="m-0 list-none p-0">
        {filteredNotes.map((note) => {
          const locationLabel = `${note.book_name || BIBLE_BOOKS[note.book]?.ko || note.book} ${note.chapter}장`
          const preview = truncate(note.content, 120)

          return (
            <li
              key={note.id}
              className="border-b border-[var(--color-border)] bg-[var(--color-bg-card)] transition-colors last:border-b-0 hover:bg-[var(--color-bg-hover)]"
            >
              <Link href={`/bible/notes/${note.id}`} className="block px-4 py-4">
                <div className="mb-2 flex items-center justify-between gap-3">
                  <p className="text-[0.9375rem] font-semibold text-[var(--color-accent-primary)]">{locationLabel}</p>
                  <p className="shrink-0 text-xs text-[var(--color-text-muted)]">{formatRelativeDate(note.updated_at)}</p>
                </div>
                <p className="line-clamp-2 text-[0.875rem] leading-relaxed text-[var(--color-text-primary)]">{preview}</p>
                <div className="mt-2 flex items-center gap-2">
                  {note.is_private ? (
                    <span className="inline-flex items-center gap-1 text-xs text-[var(--color-text-muted)]">
                      <Lock size={12} aria-hidden="true" />
                      비공개
                    </span>
                  ) : null}
                </div>
              </Link>
            </li>
          )
        })}
      </ul>
    </BibleSubpageLayout>
  )
}

// frontend/app/pages/bible/notes/index.vue
<template>
  <BibleSubpageLayout title="묵상노트">
    <!-- 필터 -->
    <template #filter>
      <div class="filter-bar">
        <select v-model="filterBook" class="filter-select">
          <option value="">전체</option>
          <optgroup label="구약">
            <option v-for="book in BIBLE_BOOKS.old" :key="book.id" :value="book.id">
              {{ book.name }}
            </option>
          </optgroup>
          <optgroup label="신약">
            <option v-for="book in BIBLE_BOOKS.new" :key="book.id" :value="book.id">
              {{ book.name }}
            </option>
          </optgroup>
        </select>
      </div>
    </template>

    <!-- 로딩 -->
    <template v-if="isLoading">
      <SkeletonList :count="5" variant="note" />
    </template>

    <!-- 로그인 필요 -->
    <EmptyState
      v-else-if="!auth.isAuthenticated.value"
      text="로그인 후 묵상노트를 확인할 수 있습니다"
      fullscreen
    >
      <template #icon>
        <DocumentIcon :size="48" />
      </template>
      <template #action>
        <NuxtLink to="/login" class="bible-login-btn">로그인</NuxtLink>
      </template>
    </EmptyState>

    <!-- 빈 상태 -->
    <EmptyState
      v-else-if="filteredNotes.length === 0"
      :text="filterBook ? '해당 책에 작성된 묵상노트가 없습니다' : '작성된 묵상노트가 없습니다'"
      hint="말씀을 읽고 묵상을 기록해보세요"
      :guide="!filterBook ? ['성경 읽기 화면으로 이동하세요', '상단 메뉴(⋮)를 탭하세요', '묵상노트 버튼을 선택하세요'] : undefined"
      fullscreen
    >
      <template #icon>
        <DocumentIcon :size="48" />
      </template>
    </EmptyState>

    <!-- 노트 목록 -->
    <ul v-else class="note-list">
      <li
        v-for="note in filteredNotes"
        :key="note.id"
        class="note-item"
        @click="goToNote(note.id)"
      >
        <div class="note-header">
          <span class="note-location">
            {{ note.book_name || getBookName(note.book) }} {{ note.chapter }}장
          </span>
          <span class="note-date">{{ formatRelativeDate(note.updated_at) }}</span>
        </div>
        <p class="note-preview">{{ truncate(note.content, 120) }}</p>
        <div class="note-meta">
          <span v-if="note.is_private" class="private-badge">
            <LockIcon :size="12" />
            비공개
          </span>
        </div>
      </li>
    </ul>

    <Toast />
  </BibleSubpageLayout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useNote } from '~/composables/useNote';
import { useBibleData, BIBLE_BOOKS } from '~/composables/useBibleData';
import { useAuthService } from '~/composables/useAuthService';
import { useTextUtils } from '~/composables/useTextUtils';
import BibleSubpageLayout from '~/components/bible/BibleSubpageLayout.vue';
import Toast from '~/components/Toast.vue';
import SkeletonList from '~/components/ui/skeleton/SkeletonList.vue';
import type { Note } from '~/types/bible';

definePageMeta({
  layout: 'default'
});

const router = useRouter();
const auth = useAuthService();
const { notes, isNoteLoading: isLoading, fetchNotes } = useNote();
const { getBookName } = useBibleData();
const { truncate } = useTextUtils();

const filterBook = ref('');

onMounted(async () => {
  if (auth.isAuthenticated.value) {
    await fetchNotes();
  }
});

const filteredNotes = computed(() => {
  if (!filterBook.value) return notes.value;
  return notes.value.filter(n => n.book === filterBook.value);
});

const goToNote = (id: number) => {
  router.push(`/bible/notes/${id}`);
};

const { formatRelativeDate } = useDateFormat();
</script>

<style scoped>
/*
 * Notes List Page specific styles
 * 공통 스타일은 bible-page.css에서 관리됨
 */

/* 필터 */
.filter-bar {
  padding: 0.75rem 1rem;
  background: var(--color-bg-card, #fff);
  border-bottom: 1px solid var(--color-border, #e5e7eb);
}

.filter-select {
  width: 100%;
  padding: 0.625rem 0.75rem;
  border: 1px solid var(--color-border, #e5e7eb);
  border-radius: 8px;
  font-size: 0.9375rem;
  color: var(--text-primary, #1f2937);
  background: var(--color-bg-card, #fff);
  cursor: pointer;
}

.filter-select:focus {
  outline: none;
  border-color: var(--primary-color, #2A1111);
}

/* 노트 목록 */
.note-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.note-item {
  padding: 1rem;
  background: var(--color-bg-card, #fff);
  border-bottom: 1px solid var(--color-border, #e5e7eb);
  cursor: pointer;
  transition: background 0.2s;
}

.note-item:hover {
  background: var(--color-bg-hover, #f9fafb);
}

.note-item:last-child {
  border-bottom: none;
}

.note-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 0.5rem;
}

.note-location {
  font-size: 0.9375rem;
  font-weight: 600;
  color: var(--primary-color, #2A1111);
}

.note-date {
  font-size: 0.75rem;
  color: var(--text-muted, #9ca3af);
}

.note-preview {
  font-size: 0.875rem;
  color: var(--text-primary, #1f2937);
  line-height: 1.5;
  margin: 0 0 0.5rem;
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.note-meta {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.private-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.75rem;
  color: var(--text-muted, #9ca3af);
}

/* 다크모드 */
:root.dark .filter-bar {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .filter-select {
  background: var(--color-bg-secondary);
  border-color: var(--color-border);
  color: var(--text-primary);
}

:root.dark .note-item {
  background: var(--color-bg-card);
  border-color: var(--color-border);
}

:root.dark .note-item:hover {
  background: var(--color-bg-hover);
}
</style>
