// maeil1dok-next/src/components/profile/ProfileEditModal.tsx
'use client'

import { useEffect, useState } from 'react'
import { User } from 'lucide-react'
import { Modal } from '@/components/ui/Modal'
import Button from '@/components/ui/Button'
import type { UserProfile } from '@/types'

interface ProfileEditModalProps {
  isOpen: boolean
  onClose: () => void
  profile: UserProfile
  onSave: (profile: UserProfile) => void
}

export function ProfileEditModal({
  isOpen,
  onClose,
  profile,
  onSave,
}: ProfileEditModalProps) {
  const [bio, setBio] = useState(profile.bio || '')
  const [isPublic, setIsPublic] = useState(profile.isPublic)
  const [error, setError] = useState('')
  const [isSaving, setIsSaving] = useState(false)

  useEffect(() => {
    if (!isOpen) return
    setBio(profile.bio || '')
    setIsPublic(profile.isPublic)
    setError('')
  }, [isOpen, profile.bio, profile.isPublic])

  const handleSave = async () => {
    setIsSaving(true)
    setError('')

    try {
      const res = await fetch('/api/profile/update', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          nickname: profile.nickname,
          bio: bio.trim(),
          isPublic,
        }),
      })

      if (!res.ok) {
        setError('저장 중 오류가 발생했습니다')
        return
      }

      const updated = (await res.json()) as UserProfile
      onSave(updated)
      onClose()
    } catch {
      setError('저장 중 오류가 발생했습니다')
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="sm">
      <Modal.Header>
        <h2 className="text-lg font-bold text-[var(--color-text-primary)]">프로필 편집</h2>
      </Modal.Header>
      <Modal.Body>
        <div className="flex flex-col gap-5">
          <div className="space-y-2">
            <p className="text-sm font-semibold text-[var(--color-text-primary)]">프로필 이미지</p>
            <div className="flex items-center gap-4">
              {profile.avatarUrl ? (
                <img
                  src={profile.avatarUrl}
                  alt={profile.nickname}
                  className="h-16 w-16 rounded-full border-2 border-[var(--color-border-default)] object-cover"
                />
              ) : (
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[var(--color-bg-secondary)] text-[var(--color-text-secondary)]">
                  <User size={28} aria-hidden="true" />
                </div>
              )}
              <p className="text-sm text-[var(--color-text-secondary)]">소셜 로그인 계정에서 가져옵니다.</p>
            </div>
          </div>

          <div className="space-y-2">
            <label htmlFor="profile-nickname" className="text-sm font-semibold text-[var(--color-text-primary)]">
              닉네임
            </label>
            <input
              id="profile-nickname"
              type="text"
              value={profile.nickname}
              disabled
              className="h-10 w-full rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)] px-3 text-sm text-[var(--color-text-secondary)]"
            />
          </div>

          <div className="space-y-2">
            <label htmlFor="profile-bio" className="text-sm font-semibold text-[var(--color-text-primary)]">
              자기소개
            </label>
            <textarea
              id="profile-bio"
              value={bio}
              onChange={(event) => setBio(event.target.value)}
              rows={4}
              maxLength={500}
              placeholder="자신을 소개해주세요 (최대 500자)"
              className="min-h-[100px] w-full resize-y rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-card)] px-3 py-2 text-sm text-[var(--color-text-primary)] outline-none transition-all placeholder:text-[var(--color-text-secondary)] focus-visible:border-[var(--color-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary)]/30"
            />
            <p className="text-right text-sm text-[var(--color-text-secondary)]">{bio.length}/500</p>
          </div>

          <div>
            <label className="flex cursor-pointer items-center gap-2.5 text-sm text-[var(--color-text-primary)]">
              <input
                type="checkbox"
                checked={isPublic}
                onChange={(event) => setIsPublic(event.target.checked)}
                className="h-[18px] w-[18px] accent-[var(--color-primary)]"
              />
              프로필 공개
            </label>
            <p className="ml-7 mt-1 text-sm text-[var(--color-text-secondary)]">
              비공개로 설정하면 팔로워만 프로필을 볼 수 있습니다.
            </p>
          </div>

           {error ? (
             <p className="rounded-lg border border-[var(--color-error-border)] bg-[var(--color-error-bg)] px-3 py-2 text-sm text-[var(--color-error-text)]">{error}</p>
           ) : null}
        </div>
      </Modal.Body>
      <Modal.Footer>
        <div className="flex w-full justify-end gap-3">
          <Button variant="secondary" onClick={onClose} className="h-10 rounded-lg px-5 text-sm">
            취소
          </Button>
          <Button
            onClick={handleSave}
            loading={isSaving}
            className="h-10 rounded-lg bg-[var(--color-primary)] px-5 text-sm text-white"
          >
            저장
          </Button>
        </div>
      </Modal.Footer>
    </Modal>
  )
}

// frontend/app/components/profile/ProfileEditModal.vue
<template>
  <BaseModal
    :model-value="true"
    title="프로필 편집"
    size="md"
    :close-on-overlay="true"
    :close-on-esc="true"
    @update:model-value="handleClose"
    @close="handleClose"
  >
    <form @submit.prevent="handleSubmit" class="profile-edit-form">
      <!-- 프로필 이미지 -->
      <div class="form-group">
        <label class="form-label">프로필 이미지</label>
        <div class="avatar-section">
          <div class="avatar-wrapper">
            <NuxtImg
              v-if="profile.user.profile_image && !imageError"
              :src="profile.user.profile_image"
              :alt="profile.user.nickname"
              class="avatar-image"
              loading="lazy"
              @error="handleImageError"
            />
            <div v-else class="avatar-placeholder">
              <UserIcon :size="32" />
            </div>
          </div>
          <p class="form-hint">소셜 로그인 계정에서 가져옵니다.</p>
        </div>
      </div>

      <!-- 닉네임 (읽기 전용) -->
      <div class="form-group">
        <label class="form-label">닉네임</label>
        <input
          type="text"
          :value="profile.user.nickname"
          disabled
          class="form-input disabled"
        >
      </div>

      <!-- 자기소개 -->
      <div class="form-group">
        <label for="bio" class="form-label">자기소개</label>
        <textarea
          id="bio"
          v-model="bio"
          rows="4"
          maxlength="500"
          class="form-textarea"
          placeholder="자신을 소개해주세요 (최대 500자)"
        ></textarea>
        <p class="form-hint char-count">{{ bio.length }}/500</p>
      </div>

      <!-- 프로필 공개 설정 -->
      <div class="form-group">
        <label class="checkbox-label">
          <input
            type="checkbox"
            v-model="isPublic"
            class="checkbox-input"
          >
          <span>프로필 공개</span>
        </label>
        <p class="form-hint checkbox-hint">
          비공개로 설정하면 팔로워만 프로필을 볼 수 있습니다.
        </p>
      </div>
    </form>

    <template #footer>
      <div class="modal-footer-content">
        <AppButton variant="secondary" size="md" @click="handleClose">취소</AppButton>
        <AppButton variant="primary" size="md" :loading="isSaving" @click="handleSubmit">
          {{ isSaving ? '저장 중...' : '저장' }}
        </AppButton>
      </div>
    </template>
  </BaseModal>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useProfileStore } from '~/stores/profile'
import { useModal } from '~/composables/useModal'
import BaseModal from '~/components/ui/modal/BaseModal.vue'
import AppButton from '~/components/ui/AppButton.vue'
import { UserIcon } from '@lucide/vue'

interface ProfileData {
  user: {
    id: number
    nickname: string
    profile_image?: string
  }
  bio: string
  is_public: boolean
}

const props = defineProps<{
  profile: ProfileData
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'saved'): void
}>()

const profileStore = useProfileStore()
const modal = useModal()

const bio = ref('')
const isPublic = ref(true)
const isSaving = ref(false)
const imageError = ref(false)

const handleClose = () => {
  emit('close')
}

const handleImageError = () => {
  imageError.value = true
}

onMounted(() => {
  bio.value = props.profile.bio || ''
  isPublic.value = props.profile.is_public
})

const handleSubmit = async () => {
  isSaving.value = true

  try {
    const result = await profileStore.updateProfile(bio.value, isPublic.value)

    if (result.success) {
      emit('saved')
      emit('close')
    } else {
      await modal.alert({
        title: '저장 실패',
        description: result.error || '프로필 저장에 실패했습니다.',
        icon: 'error'
      })
    }
  } catch (error) {
    await modal.alert({
      title: '오류 발생',
      description: '프로필 저장 중 오류가 발생했습니다.',
      icon: 'error'
    })
  } finally {
    isSaving.value = false
  }
}
</script>

<style scoped>
.profile-edit-form { display: flex; flex-direction: column; gap: 20px; letter-spacing: var(--tracking-body); }
.form-group { display: flex; flex-direction: column; gap: 8px; }
.form-label { font-size: 12px; font-weight: 600; color: var(--color-text-secondary); }
.avatar-section { display: flex; align-items: center; gap: 16px; }
.avatar-wrapper { width: 64px; height: 64px; border-radius: 50%; overflow: hidden; flex-shrink: 0; }
.avatar-image { width: 100%; height: 100%; object-fit: cover; }
.avatar-placeholder { width: 100%; height: 100%; display: grid; place-items: center; background: var(--color-accent-primary-light); color: var(--color-accent-primary); }
.form-input,
.form-textarea { padding: 12px 20px; border: 1px solid var(--color-border-default); font: inherit; font-size: 15px; color: var(--color-text-primary); background: var(--color-bg-card); transition: border-color var(--duration-micro) ease; }
.form-input { min-height: var(--hit-min); border-radius: var(--radius-pill); }
.form-textarea { min-height: 100px; border-radius: var(--radius-card); resize: vertical; }
.form-input.disabled { background: var(--color-bg-tertiary); color: var(--color-text-tertiary); cursor: not-allowed; }
.form-input:focus-visible,
.form-textarea:focus-visible,
.checkbox-input:focus-visible { outline: 3px solid var(--color-accent-focus-ring); outline-offset: 2px; border-color: var(--color-accent-primary); }
.form-hint { margin: 0; font-size: 13px; color: var(--color-text-secondary); }
.char-count { text-align: right; font-variant-numeric: tabular-nums; }
.checkbox-label { display: flex; align-items: center; gap: 10px; min-height: var(--hit-min); cursor: pointer; font-size: 15px; color: var(--color-text-primary); }
.checkbox-input { width: 18px; height: 18px; accent-color: var(--color-accent-primary); cursor: pointer; }
.checkbox-hint { margin-left: 28px; }
.modal-footer-content { display: flex; justify-content: flex-end; gap: 8px; width: 100%; }
@media (prefers-reduced-motion: reduce) {
  .form-input,
  .form-textarea { transition: none; }
}
</style>
