// frontend/app/pages/company.vue
<template>
  <PageLayout title="회사정보" fallback-path="/">
    <div class="legal-page">
      <div class="bg-pattern"></div>
      <main class="main-content">
        <div class="card fade-in" style="animation-delay: 0.1s">
          <h1 class="page-title">Company Info</h1>
          <p class="page-subtitle">회사정보</p>

          <div class="info-grid">
            <div class="info-item">
              <span class="info-label">Company Name</span>
              <span class="info-value">제이지피랩스</span>
            </div>
            <div class="info-item">
              <span class="info-label">Representative</span>
              <span class="info-value">박지건</span>
            </div>
            <div class="info-item">
              <span class="info-label">Business Registration No.</span>
              <span class="info-value">613-24-62749</span>
            </div>
            <div class="info-item">
              <span class="info-label">Mail-Order Sales No.</span>
              <span class="info-value">제 2022-용인기흥-1517 호</span>
            </div>
            <div class="info-item">
              <span class="info-label">Address</span>
              <span class="info-value">경기도 용인시 기흥구 동백4로 6, 6105호</span>
            </div>
            <div class="info-item">
              <span class="info-label">Phone</span>
              <span class="info-value">010-2368-9677</span>
            </div>
            <div class="info-item">
              <span class="info-label">Email</span>
              <span class="info-value">support@maeil1dok.app</span>
            </div>
            <div class="info-item">
              <span class="info-label">Privacy Officer</span>
              <span class="info-value">박지건</span>
            </div>
            <div class="info-item">
              <span class="info-label">Business Verification</span>
              <span class="info-value">
                <a 
                  href="https://www.ftc.go.kr/bizCommPop.do?wrkr_no=6132462749" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  class="external-link"
                >
                  사업자정보확인 &rarr;
                </a>
              </span>
            </div>
            <div class="info-item">
              <span class="info-label">Hosting Provider</span>
              <span class="info-value">Vercel Inc.</span>
            </div>
          </div>
        </div>

        <div class="link-section fade-in" style="animation-delay: 0.2s">
          <NuxtLink to="/privacy" class="link-button">개인정보처리방침</NuxtLink>
          <NuxtLink to="/terms" class="link-button">이용약관</NuxtLink>
          <NuxtLink to="/" class="link-button">홈으로</NuxtLink>
        </div>
      </main>
    </div>
  </PageLayout>
</template>

<script setup>
import { useHead } from '#imports'
import PageLayout from '~/components/common/PageLayout.vue'

useHead({
  title: '회사정보 - 매일일독',
  meta: [
    { name: 'description', content: '매일일독 서비스를 운영하는 제이지피랩스의 회사 정보입니다.' },
    { property: 'og:title', content: '회사정보 - 매일일독' },
    { property: 'og:description', content: '매일일독 서비스를 운영하는 제이지피랩스의 회사 정보입니다.' },
    { property: 'og:url', content: 'https://maeil1dok.app/company' },
    { property: 'og:type', content: 'website' },
  ],
})
</script>

<style scoped>
.legal-page {
  font-family: 'Pretendard', sans-serif;
  background-color: var(--color-bg-primary);
  color: var(--color-text-primary);
  min-height: 100vh;
  position: relative;
  -webkit-font-smoothing: antialiased;
}

.bg-pattern {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-image: radial-gradient(var(--color-text-tertiary) 1px, transparent 1px);
  background-size: 32px 32px;
  opacity: 0.1;
  z-index: 0;
  pointer-events: none;
}

.main-content {
  padding: 1.5rem 1rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.card {
  background: var(--color-bg-card);
  border-radius: 20px;
  box-shadow: var(--shadow-md);
  overflow: hidden;
  border: 1px solid var(--color-border-light);
  padding: 2rem;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-text-primary);
  margin: 0 0 0.25rem 0;
}

.page-subtitle {
  font-size: 0.95rem;
  color: var(--color-text-secondary);
  margin: 0 0 2rem 0;
}

.info-grid {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid var(--color-border-light);
}

.info-item:last-child {
  border-bottom: none;
  padding-bottom: 0;
}

.info-label {
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--color-text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.info-value {
  font-size: 1rem;
  color: var(--color-text-primary);
}

.external-link {
  color: var(--color-accent-primary);
  text-decoration: none;
  transition: opacity 0.2s;
}

.external-link:hover {
  opacity: 0.8;
}

.link-section {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  justify-content: center;
}

.link-button {
  padding: 0.6rem 1.25rem;
  background: var(--color-bg-tertiary);
  color: var(--color-text-secondary);
  border: 1px solid var(--color-border-default);
  border-radius: 99px;
  font-size: 0.9rem;
  font-weight: 500;
  text-decoration: none;
  transition: all 0.2s ease;
}

.link-button:hover {
  background: var(--color-bg-hover);
  color: var(--color-text-primary);
  border-color: var(--color-border-dark);
}

/* Animations */
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}

.fade-in {
  opacity: 0;
  animation: fadeIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;
}
</style>

// maeil1dok-next/src/app/(public)/company/page.tsx
'use client'

import PageHeader from '@/components/ui/PageHeader'
import Link from 'next/link'

export default function CompanyPage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      <PageHeader title="회사정보" fallback-path="/" />

      <div className="max-w-[768px] mx-auto px-4 py-6">
        <div className="bg-[var(--color-bg-card)] rounded-[20px] shadow-[var(--shadow-md)] border border-[var(--color-border-light)] p-8">
          <h1 className="text-2xl font-bold text-[var(--color-text-primary)] mb-1">Company Info</h1>
          <p className="text-sm text-[var(--color-text-secondary)] mb-8">회사정보</p>

          <div className="space-y-4">
            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Company Name</p>
              <p className="text-base text-[var(--color-text-primary)]">제이지피랩스</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Representative</p>
              <p className="text-base text-[var(--color-text-primary)]">박지건</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Business Registration No.</p>
              <p className="text-base text-[var(--color-text-primary)]">613-24-62749</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Mail-Order Sales No.</p>
              <p className="text-base text-[var(--color-text-primary)]">제 2022-용인기흥-1517 호</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Address</p>
              <p className="text-base text-[var(--color-text-primary)]">경기도 용인시 기흥구 동백4로 6, 6105호</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Phone</p>
              <p className="text-base text-[var(--color-text-primary)]">010-2368-9677</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Email</p>
              <p className="text-base text-[var(--color-text-primary)]">support@maeil1dok.app</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Privacy Officer</p>
              <p className="text-base text-[var(--color-text-primary)]">박지건</p>
            </div>

            <div className="pb-4 border-b border-[var(--color-border-light)]">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Business Verification</p>
              <p className="text-base text-[var(--color-text-primary)]">
                <a 
                  href="https://www.ftc.go.kr/bizCommPop.do?wrkr_no=6132462749" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-[var(--color-accent-primary)] hover:opacity-80 transition-opacity"
                >
                  사업자정보확인 →
                </a>
              </p>
            </div>

            <div className="pb-4">
              <p className="text-xs font-semibold text-[var(--color-text-tertiary)] uppercase tracking-wider mb-1">Hosting Provider</p>
              <p className="text-base text-[var(--color-text-primary)]">Vercel Inc.</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap gap-3 justify-center mt-6">
          <Link href="/privacy" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            개인정보처리방침
          </Link>
          <Link href="/terms" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            이용약관
          </Link>
          <Link href="/" className="px-5 py-2.5 bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] border border-[var(--color-border-default)] rounded-full text-sm font-medium hover:bg-[var(--color-bg-hover)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-border-dark)] transition-all">
            홈으로
          </Link>
        </div>
      </div>
    </div>
  )
}
